"""Status-safe channel account projection helpers for CLI, status APIs, and plugin SDK callers.

Mirrors src/channels/account-snapshot-fields.ts.
"""

from __future__ import annotations

from typing import Any

def resolve_configured_from_credential_statuses(*args: Any, **kwargs: Any) -> Any: ...
def resolve_configured_from_required_credential_statuses(*args: Any, **kwargs: Any) -> Any: ...
def has_configured_unavailable_credential_status(*args: Any, **kwargs: Any) -> Any: ...
def has_resolved_credential_value(*args: Any, **kwargs: Any) -> Any: ...
def project_credential_snapshot_fields(*args: Any, **kwargs: Any) -> Any: ...
def project_safe_channel_account_snapshot_fields(*args: Any, **kwargs: Any) -> Any: ...
