"""Channel config matching helpers.

Mirrors src/channels/channel-config.ts.
"""

from __future__ import annotations

from typing import Any

ChannelMatchSource = Any
ChannelEntryMatch = Any

def apply_channel_match_meta(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_match_config(*args: Any, **kwargs: Any) -> Any: ...
def normalize_channel_slug(*args: Any, **kwargs: Any) -> Any: ...
def build_channel_key_candidates(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_entry_match(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_entry_match_with_fallback(*args: Any, **kwargs: Any) -> Any: ...
def resolve_nested_allowlist_decision(*args: Any, **kwargs: Any) -> Any: ...
