"""Public channel registry facade for channel ids, metadata, and setup copy.

Mirrors src/channels/registry.ts.
"""

from __future__ import annotations

from typing import Any

def normalize_channel_id(*args: Any, **kwargs: Any) -> Any: ...
def normalize_any_channel_id(*args: Any, **kwargs: Any) -> Any: ...
def list_registered_channel_plugin_ids(*args: Any, **kwargs: Any) -> Any: ...
def get_registered_channel_plugin_meta(*args: Any, **kwargs: Any) -> Any: ...
def format_channel_primer_line(*args: Any, **kwargs: Any) -> Any: ...
def format_channel_selection_line(*args: Any, **kwargs: Any) -> Any: ...
