"""Route projection helpers between sessions, delivery context, and channel routes.

Mirrors src/channels/route-projection.ts.
"""

from __future__ import annotations

from typing import Any

def format_conversation_target(*args: Any, **kwargs: Any) -> Any: ...
def resolve_conversation_delivery_target(*args: Any, **kwargs: Any) -> Any: ...
def route_from_conversation_ref(*args: Any, **kwargs: Any) -> Any: ...
def route_from_binding_record(*args: Any, **kwargs: Any) -> Any: ...
def route_to_delivery_fields(*args: Any, **kwargs: Any) -> Any: ...
