"""Channel streaming config normalization and progress-draft formatting helpers.

Mirrors src/channels/streaming.ts.
"""

from __future__ import annotations

from typing import Any

DEFAULT_PROGRESS_DRAFT_LABELS: Any = None
DEFAULT_PROGRESS_DRAFT_INITIAL_DELAY_MS: Any = None

StreamingCompatEntry = Any
ChannelProgressLineOptions = Any
ChannelProgressDraftRenderMode = Any
ChannelProgressDraftLineInput = Any
ChannelProgressDraftLineKind = Any
ChannelProgressDraftLine = Any

def is_channel_progress_draft_work_tool_name(*args: Any, **kwargs: Any) -> Any: ...
def is_potential_truncated_final(*args: Any, **kwargs: Any) -> Any: ...
def select_longer_final_text(*args: Any, **kwargs: Any) -> Any: ...
def format_channel_progress_draft_line(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_progress_draft_line_options(*args: Any, **kwargs: Any) -> Any: ...
def build_channel_progress_draft_line_for_entry(*args: Any, **kwargs: Any) -> Any: ...
def format_channel_progress_draft_line_for_entry(*args: Any, **kwargs: Any) -> Any: ...
def build_channel_progress_draft_line(*args: Any, **kwargs: Any) -> Any: ...
def create_channel_progress_draft_gate(*args: Any, **kwargs: Any) -> Any: ...
def get_channel_streaming_config_object(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_streaming_chunk_mode(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_streaming_block_enabled(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_streaming_block_coalesce(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_streaming_preview_chunk(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_streaming_preview_tool_progress(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_streaming_progress_commentary(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_streaming_preview_command_text(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_streaming_suppress_default_tool_progress_messages(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_streaming_native_transport(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_preview_stream_mode(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_progress_draft_config(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_progress_draft_label(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_progress_draft_max_lines(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_progress_draft_max_line_chars(*args: Any, **kwargs: Any) -> Any: ...
def resolve_channel_progress_draft_render(*args: Any, **kwargs: Any) -> Any: ...
def normalize_channel_progress_draft_line_identity(*args: Any, **kwargs: Any) -> Any: ...
def merge_channel_progress_draft_line(*args: Any, **kwargs: Any) -> Any: ...
def format_channel_progress_draft_text(*args: Any, **kwargs: Any) -> Any: ...
async def resolve_transcript_backed_channel_final_text(*args: Any, **kwargs: Any) -> Any: ...
