"""Shared messaging-target parsing primitives for channel plugins and SDK consumers.

Mirrors src/channels/targets.ts.
"""

from __future__ import annotations

from typing import Any

MessagingTargetKind = Any
MessagingTarget = Any
MessagingTargetParseOptions = Any

def normalize_target_id(*args: Any, **kwargs: Any) -> Any: ...
def build_messaging_target(*args: Any, **kwargs: Any) -> Any: ...
def ensure_target_id(*args: Any, **kwargs: Any) -> Any: ...
def parse_target_mention(*args: Any, **kwargs: Any) -> Any: ...
def parse_target_prefix(*args: Any, **kwargs: Any) -> Any: ...
def parse_target_prefixes(*args: Any, **kwargs: Any) -> Any: ...
def parse_at_user_target(*args: Any, **kwargs: Any) -> Any: ...
def parse_mention_prefix_or_at_user_target(*args: Any, **kwargs: Any) -> Any: ...
def require_target_kind(*args: Any, **kwargs: Any) -> Any: ...
