"""Thread-binding policy resolution for channel/account session spawning.

Mirrors src/channels/thread-bindings-policy.ts.
"""

from __future__ import annotations

from typing import Any

ThreadBindingSpawnKind = Any
ThreadBindingSpawnPolicy = Any

def supports_automatic_thread_binding_spawn(*args: Any, **kwargs: Any) -> Any: ...
def requires_native_thread_context_for_thread_here(*args: Any, **kwargs: Any) -> Any: ...
def resolve_thread_binding_placement_for_current_context(*args: Any, **kwargs: Any) -> Any: ...
def resolve_thread_binding_idle_timeout_ms(*args: Any, **kwargs: Any) -> Any: ...
def resolve_thread_binding_max_age_ms(*args: Any, **kwargs: Any) -> Any: ...
def resolve_thread_binding_effective_expires_at(*args: Any, **kwargs: Any) -> Any: ...
def resolve_thread_bindings_enabled(*args: Any, **kwargs: Any) -> Any: ...
def resolve_thread_binding_spawn_policy(*args: Any, **kwargs: Any) -> Any: ...
def resolve_thread_binding_idle_timeout_ms_for_channel(*args: Any, **kwargs: Any) -> Any: ...
def resolve_thread_binding_max_age_ms_for_channel(*args: Any, **kwargs: Any) -> Any: ...
def format_thread_binding_disabled_error(*args: Any, **kwargs: Any) -> Any: ...
def format_thread_binding_spawn_disabled_error(*args: Any, **kwargs: Any) -> Any: ...
