#!/usr/bin/env python3
"""Order migration tasks by dependency topology instead of directory listing.

The original task list was generated by walking directories, so following it
means constantly hitting imports that have no Python counterpart yet. This
resolves each module's imports back to the task that owns them, condenses
import cycles into single units, and emits a plan in dependency order.

Usage:
    python migration/depgraph.py --json migration/plan.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from ts_symbols import read_module, ts_repo

PY_ROOT = Path(__file__).resolve().parent.parent
PACKAGE_PREFIX = "@openclaw/"


def load_tasks() -> list[dict]:
    path = ts_repo() / "migration" / "progress-phase2.json"
    tasks = json.loads(path.read_text(encoding="utf-8"))["tasks"]
    return [t for t in tasks if t.get("source_paths") and t.get("target_paths")]


def build_owner_index(tasks: list[dict]) -> dict[str, str]:
    """Map each task's source directory to its task id."""
    return {task["source_paths"][0].rstrip("/"): task["id"] for task in tasks}


def resolve_import(spec: str, importer_dir: Path, repo: Path) -> Path | None:
    """Turn an import specifier into a repo-relative path, or None if external."""
    if spec.startswith("."):
        resolved = (importer_dir / spec).resolve()
    elif spec.startswith(PACKAGE_PREFIX):
        remainder = spec[len(PACKAGE_PREFIX) :]
        package, _, subpath = remainder.partition("/")
        resolved = (repo / "packages" / package / "src" / (subpath or "index")).resolve()
    else:
        return None

    try:
        return resolved.relative_to(repo.resolve())
    except ValueError:
        return None


def owner_of(path: Path, owners: dict[str, str]) -> str | None:
    """Find the task owning a path by longest matching directory prefix."""
    candidate = path.parent if path.suffix or path.name.endswith(".js") else path
    parts = candidate.parts
    for depth in range(len(parts), 0, -1):
        key = "/".join(parts[:depth])
        if key in owners:
            return owners[key]
    return None


def build_graph(tasks: list[dict]) -> tuple[dict[str, set[str]], dict[str, dict]]:
    repo = ts_repo()
    owners = build_owner_index(tasks)
    edges: dict[str, set[str]] = {task["id"]: set() for task in tasks}
    meta: dict[str, dict] = {}

    for task in tasks:
        source_rel = task["source_paths"][0]
        source_dir = repo / source_rel
        facts = read_module(source_dir)
        meta[task["id"]] = {
            "id": task["id"],
            "title": task.get("title", ""),
            "source": source_rel,
            "target": task["target_paths"][0],
            "ts_source_lines": facts.source_lines,
            "ts_api_count": len(facts.api),
            "file_count": facts.file_count,
        }

        for spec in facts.imports:
            resolved = resolve_import(spec, source_dir, repo)
            if resolved is None:
                continue
            dependency = owner_of(resolved, owners)
            if dependency and dependency != task["id"]:
                edges[task["id"]].add(dependency)

    return edges, meta


def strongly_connected_components(edges: dict[str, set[str]]) -> list[list[str]]:
    """Tarjan's algorithm, iterative to survive deep import chains."""
    index_of: dict[str, int] = {}
    low: dict[str, int] = {}
    on_stack: set[str] = set()
    stack: list[str] = []
    result: list[list[str]] = []
    counter = 0

    for root in edges:
        if root in index_of:
            continue
        work: list[tuple[str, int]] = [(root, 0)]
        while work:
            node, child_index = work[-1]
            if child_index == 0:
                index_of[node] = low[node] = counter
                counter += 1
                stack.append(node)
                on_stack.add(node)

            children = sorted(edges.get(node, ()))
            if child_index < len(children):
                work[-1] = (node, child_index + 1)
                child = children[child_index]
                if child not in index_of:
                    work.append((child, 0))
                elif child in on_stack:
                    low[node] = min(low[node], index_of[child])
                continue

            if low[node] == index_of[node]:
                component: list[str] = []
                while True:
                    member = stack.pop()
                    on_stack.discard(member)
                    component.append(member)
                    if member == node:
                        break
                result.append(sorted(component))

            work.pop()
            if work:
                parent = work[-1][0]
                low[parent] = min(low[parent], low[node])

    return result


def rank_within_cycle(
    component: list[str], edges: dict[str, set[str]], meta: dict[str, dict]
) -> list[str]:
    """Order tasks inside an import cycle so the plan stays actionable.

    Directory-level granularity turns file-level import chains into one large
    cycle that no topological sort can break. Inside it, port whatever the most
    other modules depend on first, preferring smaller modules on ties.
    """
    members = set(component)
    fan_in = {node: 0 for node in component}
    for node in component:
        for dep in edges[node] & members:
            fan_in[dep] += 1
    return sorted(component, key=lambda n: (-fan_in[n], meta[n]["ts_source_lines"], n))


def order_components(
    components: list[list[str]], edges: dict[str, set[str]], meta: dict[str, dict]
) -> list[list[str]]:
    """Topologically sort condensed components, smallest work first on ties."""
    component_of = {node: i for i, comp in enumerate(components) for node in comp}
    condensed: dict[int, set[int]] = {i: set() for i in range(len(components))}
    for node, deps in edges.items():
        src = component_of[node]
        for dep in deps:
            dst = component_of.get(dep)
            if dst is not None and dst != src:
                condensed[src].add(dst)

    def weight(index: int) -> tuple[int, str]:
        comp = components[index]
        return (sum(meta[n]["ts_source_lines"] for n in comp), comp[0])

    remaining = dict(condensed)
    ordered: list[list[str]] = []
    while remaining:
        ready = [i for i, deps in remaining.items() if not (deps & remaining.keys())]
        if not ready:
            # Should not happen after condensation, but never spin forever.
            ready = [min(remaining, key=weight)]
        for index in sorted(ready, key=weight):
            ordered.append(components[index])
            del remaining[index]

    return ordered


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", type=Path, default=None)
    parser.add_argument("--audit", type=Path, default=Path("migration/audit.json"))
    args = parser.parse_args()

    if not ts_repo().is_dir():
        print(f"missing TypeScript repo at {ts_repo()}", file=sys.stderr)
        return 1

    tasks = load_tasks()
    edges, meta = build_graph(tasks)
    components = strongly_connected_components(edges)
    ordered = order_components(components, edges, meta)

    grades: dict[str, str] = {}
    if args.audit.is_file():
        grades = {
            row["id"]: row["grade"] for row in json.loads(args.audit.read_text(encoding="utf-8"))
        }

    plan: list[dict] = []
    position = 0
    for component in ordered:
        for task_id in rank_within_cycle(component, edges, meta):
            position += 1
            entry = dict(meta[task_id])
            entry["order"] = position
            entry["cycle_size"] = len(component)
            entry["depends_on"] = sorted(edges[task_id])
            entry["grade"] = grades.get(task_id, "unknown")
            nothing_to_port = entry["ts_source_lines"] == 0 and entry["ts_api_count"] == 0
            entry["status"] = (
                "done" if entry["grade"] == "ported" or nothing_to_port else "pending"
            )
            plan.append(entry)

    cycles = [c for c in ordered if len(c) > 1]
    print(f"{len(tasks)} tasks -> {len(ordered)} dependency levels")
    print(
        f"import cycles: {len(cycles)} (largest {max((len(c) for c in cycles), default=0)} tasks)"
    )

    pending = [p for p in plan if p["status"] == "pending"]
    print(
        f"pending after audit: {len(pending)} tasks, "
        f"{sum(p['ts_source_lines'] for p in pending):,} TypeScript source lines\n"
    )

    print(
        f"first 20 in dependency order:\n{'#':>4} {'task':10} {'module':46} {'grade':9} {'lines':>7}"
    )
    for entry in plan[:20]:
        print(
            f"{entry['order']:4} {entry['id']:10} {entry['source'][:46]:46} "
            f"{entry['grade']:9} {entry['ts_source_lines']:7}"
        )

    if args.json:
        args.json.write_text(json.dumps(plan, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"\nwrote {args.json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
