from __future__ import annotations

from typing import Any


class AgentCompactionConstants:
    DEFAULT_MAX_TOKENS = 128000
    COMPACTION_TRIGGER_TOKENS = 100000
    SAFETY_MARGIN_TOKENS = 20000
    MIN_COMPACTION_TOKENS = 8000


DEFAULT_MAX_TOKENS = AgentCompactionConstants.DEFAULT_MAX_TOKENS
COMPACTION_TRIGGER_TOKENS = AgentCompactionConstants.COMPACTION_TRIGGER_TOKENS
SAFETY_MARGIN_TOKENS = AgentCompactionConstants.SAFETY_MARGIN_TOKENS
MIN_COMPACTION_TOKENS = AgentCompactionConstants.MIN_COMPACTION_TOKENS
