from typing import Literal, Final

AGENT_RUN_BLOCKED: Literal["AGENT_RUN_BLOCKED"] = "AGENT_RUN_BLOCKED"
AGENT_VERSION_OUT_OF_DATE: Literal["AGENT_VERSION_OUT_OF_DATE"] = "AGENT_VERSION_OUT_OF_DATE"
APPROVAL_LOCKED: Literal["APPROVAL_LOCKED"] = "APPROVAL_LOCKED"
APPROVAL_LOCK_TIMEOUT: Literal["APPROVAL_LOCK_TIMEOUT"] = "APPROVAL_LOCK_TIMEOUT"
APPROVAL_REJECTED: Literal["APPROVAL_REJECTED"] = "APPROVAL_REJECTED"
APPROVAL_REQUIRED: Literal["APPROVAL_REQUIRED"] = "APPROVAL_REQUIRED"
APPROVAL_REVOKED: Literal["APPROVAL_REVOKED"] = "APPROVAL_REVOKED"
APPROVAL_RUN_MISMATCH: Literal["APPROVAL_RUN_MISMATCH"] = "APPROVAL_RUN_MISMATCH"
APPROVAL_RUN_NOT_FOUND: Literal["APPROVAL_RUN_NOT_FOUND"] = "APPROVAL_RUN_NOT_FOUND"
APPROVAL_RUN_NOT_PENDING: Literal["APPROVAL_RUN_NOT_PENDING"] = "APPROVAL_RUN_NOT_PENDING"
ARTIFACT_IN_USE_BY_RUN: Literal["ARTIFACT_IN_USE_BY_RUN"] = "ARTIFACT_IN_USE_BY_RUN"
ARTIFACT_NOT_FOUND: Literal["ARTIFACT_NOT_FOUND"] = "ARTIFACT_NOT_FOUND"
ARTIFACT_PUSH_FAILED: Literal["ARTIFACT_PUSH_FAILED"] = "ARTIFACT_PUSH_FAILED"
ARTIFACT_PUSH_UNAUTHORIZED: Literal["ARTIFACT_PUSH_UNAUTHORIZED"] = "ARTIFACT_PUSH_UNAUTHORIZED"
ARTIFACT_UPLOAD_UNAVAILABLE: Literal["ARTIFACT_UPLOAD_UNAVAILABLE"] = "ARTIFACT_UPLOAD_UNAVAILABLE"
AUTH_REQUIRED: Literal["AUTH_REQUIRED"] = "AUTH_REQUIRED"
AUTH_UNAUTHORIZED: Literal["AUTH_UNAUTHORIZED"] = "AUTH_UNAUTHORIZED"
AWARD_REJECTED: Literal["AWARD_REJECTED"] = "AWARD_REJECTED"
AWARD_REQUIRED: Literal["AWARD_REQUIRED"] = "AWARD_REQUIRED"
AWARD_REVOKED: Literal["AWARD_REVOKED"] = "AWARD_REVOKED"
AWARD_RUN_MISMATCH: Literal["AWARD_RUN_MISMATCH"] = "AWARD_RUN_MISMATCH"
AWARD_RUN_NOT_FOUND: Literal["AWARD_RUN_NOT_FOUND"] = "AWARD_RUN_NOT_FOUND"
AWARD_RUN_NOT_PENDING: Literal["AWARD_RUN_NOT_PENDING"] = "AWARD_RUN_NOT_PENDING"
BAD_REQUEST: Literal["BAD_REQUEST"] = "BAD_REQUEST"
CA_CERT_EXPIRED: Literal["CA_CERT_EXPIRED"] = "CA_CERT_EXPIRED"
CA_CERT_UNTRUSTED: Literal["CA_CERT_UNTRUSTED"] = "CA_CERT_UNTRUSTED"
CA_CERT_VALIDATION_FAILED: Literal["CA_CERT_VALIDATION_FAILED"] = "CA_CERT_VALIDATION_FAILED"
CAPABILITY_DISABLED: Literal["CAPABILITY_DISABLED"] = "CAPABILITY_DISABLED"
CAPABILITY_NOT_SUPPORTED: Literal["CAPABILITY_NOT_SUPPORTED"] = "CAPABILITY_NOT_SUPPORTED"
CA_CERT_MISSING: Literal["CA_CERT_MISSING"] = "CA_CERT_MISSING"
CA_CERT_REQUIRED: Literal["CA_CERT_REQUIRED"] = "CA_CERT_REQUIRED"
CA_CERT_VALIDATION_UNAVAILABLE: Literal["CA_CERT_VALIDATION_UNAVAILABLE"] = "CA_CERT_VALIDATION_UNAVAILABLE"
CHAT_SESSION_CLOSED: Literal["CHAT_SESSION_CLOSED"] = "CHAT_SESSION_CLOSED"
CHAT_SESSION_NOT_FOUND: Literal["CHAT_SESSION_NOT_FOUND"] = "CHAT_SESSION_NOT_FOUND"
CLEANUP_FAILED: Literal["CLEANUP_FAILED"] = "CLEANUP_FAILED"
COMMIT_BLOCKED: Literal["COMMIT_BLOCKED"] = "COMMIT_BLOCKED"
CONFIG_PARSE_FAILED: Literal["CONFIG_PARSE_FAILED"] = "CONFIG_PARSE_FAILED"
CONFIG_SCHEMA_INVALID: Literal["CONFIG_SCHEMA_INVALID"] = "CONFIG_SCHEMA_INVALID"
CONFLICT: Literal["CONFLICT"] = "CONFLICT"
CONNECT_BLOCKED: Literal["CONNECT_BLOCKED"] = "CONNECT_BLOCKED"
CONNECT_FAILED: Literal["CONNECT_FAILED"] = "CONNECT_FAILED"
CONNECT_NOT_FOUND: Literal["CONNECT_NOT_FOUND"] = "CONNECT_NOT_FOUND"
CONNECT_REJECTED: Literal["CONNECT_REJECTED"] = "CONNECT_REJECTED"
CONNECT_REQUIRED: Literal["CONNECT_REQUIRED"] = "CONNECT_REQUIRED"
CONNECT_TIMEOUT: Literal["CONNECT_TIMEOUT"] = "CONNECT_TIMEOUT"
CONNECT_UNAUTHORIZED: Literal["CONNECT_UNAUTHORIZED"] = "CONNECT_UNAUTHORIZED"
CONNECT_UNAVAILABLE: Literal["CONNECT_UNAVAILABLE"] = "CONNECT_UNAVAILABLE"
CRON_DISABLED: Literal["CRON_DISABLED"] = "CRON_DISABLED"
CRON_NOT_FOUND: Literal["CRON_NOT_FOUND"] = "CRON_NOT_FOUND"
CRON_NOT_SUPPORTED: Literal["CRON_NOT_SUPPORTED"] = "CRON_NOT_SUPPORTED"
CRON_PARSE_FAILED: Literal["CRON_PARSE_FAILED"] = "CRON_PARSE_FAILED"
DEADLINE_EXCEEDED: Literal["DEADLINE_EXCEEDED"] = "DEADLINE_EXCEEDED"
DEBUG_SESSION_NOT_FOUND: Literal["DEBUG_SESSION_NOT_FOUND"] = "DEBUG_SESSION_NOT_FOUND"
DEBUG_SESSION_NOT_SUPPORTED: Literal["DEBUG_SESSION_NOT_SUPPORTED"] = "DEBUG_SESSION_NOT_SUPPORTED"
DEVICE_PAIR_FAILED: Literal["DEVICE_PAIR_FAILED"] = "DEVICE_PAIR_FAILED"
DEVICE_PAIR_NOT_SUPPORTED: Literal["DEVICE_PAIR_NOT_SUPPORTED"] = "DEVICE_PAIR_NOT_SUPPORTED"
DEVICE_PAIR_REVOKED: Literal["DEVICE_PAIR_REVOKED"] = "DEVICE_PAIR_REVOKED"
DEVICE_REVOKED: Literal["DEVICE_REVOKED"] = "DEVICE_REVOKED"
DEVICE_TRUST_FAILED: Literal["DEVICE_TRUST_FAILED"] = "DEVICE_TRUST_FAILED"
DEVICE_TRUST_NOT_SUPPORTED: Literal["DEVICE_TRUST_NOT_SUPPORTED"] = "DEVICE_TRUST_NOT_SUPPORTED"
DEVICE_TRUST_REVOKED: Literal["DEVICE_TRUST_REVOKED"] = "DEVICE_TRUST_REVOKED"
DIRECTORY_IN_USE_BY_RUN: Literal["DIRECTORY_IN_USE_BY_RUN"] = "DIRECTORY_IN_USE_BY_RUN"
DIRECTORY_NOT_FOUND: Literal["DIRECTORY_NOT_FOUND"] = "DIRECTORY_NOT_FOUND"
DIRECTORY_UPLOAD_UNAVAILABLE: Literal["DIRECTORY_UPLOAD_UNAVAILABLE"] = "DIRECTORY_UPLOAD_UNAVAILABLE"
DISCONNECT_REQUIRED: Literal["DISCONNECT_REQUIRED"] = "DISCONNECT_REQUIRED"
DOES_NOT_EXIST: Literal["DOES_NOT_EXIST"] = "DOES_NOT_EXIST"
DOWNSTREAM_DEPENDENCY_FAILED: Literal["DOWNSTREAM_DEPENDENCY_FAILED"] = "DOWNSTREAM_DEPENDENCY_FAILED"
DOWNSTREAM_DEPENDENCY_UNAVAILABLE: Literal["DOWNSTREAM_DEPENDENCY_UNAVAILABLE"] = "DOWNSTREAM_DEPENDENCY_UNAVAILABLE"
DOWNSTREAM_PROTOCOL_NEGOTIATION_FAILED: Literal["DOWNSTREAM_PROTOCOL_NEGOTIATION_FAILED"] = "DOWNSTREAM_PROTOCOL_NEGOTIATION_FAILED"
DOWNSTREAM_PROTOCOL_VERSION_UNSUPPORTED: Literal["DOWNSTREAM_PROTOCOL_VERSION_UNSUPPORTED"] = "DOWNSTREAM_PROTOCOL_VERSION_UNSUPPORTED"
DOWNSTREAM_QUOTA_EXCEEDED: Literal["DOWNSTREAM_QUOTA_EXCEEDED"] = "DOWNSTREAM_QUOTA_EXCEEDED"
DOWNSTREAM_RATE_LIMITED: Literal["DOWNSTREAM_RATE_LIMITED"] = "DOWNSTREAM_RATE_LIMITED"
DOWNSTREAM_UNREACHABLE: Literal["DOWNSTREAM_UNREACHABLE"] = "DOWNSTREAM_UNREACHABLE"
DOWNSTREAM_UPSTREAM_AUTH_FAILED: Literal["DOWNSTREAM_UPSTREAM_AUTH_FAILED"] = "DOWNSTREAM_UPSTREAM_AUTH_FAILED"
DOWNSTREAM_UPSTREAM_AUTH_REQUIRED: Literal["DOWNSTREAM_UPSTREAM_AUTH_REQUIRED"] = "DOWNSTREAM_UPSTREAM_AUTH_REQUIRED"
ELEVATION_BLOCKED: Literal["ELEVATION_BLOCKED"] = "ELEVATION_BLOCKED"
ELEVATION_REQUIRED: Literal["ELEVATION_REQUIRED"] = "ELEVATION_REQUIRED"
ELEVATION_REVOKED: Literal["ELEVATION_REVOKED"] = "ELEVATION_REVOKED"
ENVIRONMENT_NOT_FOUND: Literal["ENVIRONMENT_NOT_FOUND"] = "ENVIRONMENT_NOT_FOUND"
EXEC_APPROVAL_BLOCKED: Literal["EXEC_APPROVAL_BLOCKED"] = "EXEC_APPROVAL_BLOCKED"
EXEC_APPROVAL_REQUIRED: Literal["EXEC_APPROVAL_REQUIRED"] = "EXEC_APPROVAL_REQUIRED"
EXEC_APPROVAL_REVOKED: Literal["EXEC_APPROVAL_REVOKED"] = "EXEC_APPROVAL_REVOKED"
EXEC_BLOCKED: Literal["EXEC_BLOCKED"] = "EXEC_BLOCKED"
EXEC_DISABLED: Literal["EXEC_DISABLED"] = "EXEC_DISABLED"
EXEC_NOT_SUPPORTED: Literal["EXEC_NOT_SUPPORTED"] = "EXEC_NOT_SUPPORTED"
EXEC_REQUIRED: Literal["EXEC_REQUIRED"] = "EXEC_REQUIRED"
EXEC_REVOKED: Literal["EXEC_REVOKED"] = "EXEC_REVOKED"
GATEWAY_BUSY: Literal["GATEWAY_BUSY"] = "GATEWAY_BUSY"
GATEWAY_NOT_AVAILABLE: Literal["GATEWAY_NOT_AVAILABLE"] = "GATEWAY_NOT_AVAILABLE"
GATEWAY_NOT_FOUND: Literal["GATEWAY_NOT_FOUND"] = "GATEWAY_NOT_FOUND"
GATEWAY_SHUTDOWN: Literal["GATEWAY_SHUTDOWN"] = "GATEWAY_SHUTDOWN"
GATEWAY_TIMEOUT: Literal["GATEWAY_TIMEOUT"] = "GATEWAY_TIMEOUT"
GATEWAY_VERSION_MISMATCH: Literal["GATEWAY_VERSION_MISMATCH"] = "GATEWAY_VERSION_MISMATCH"
HOST_CREDENTIALS_NOT_FOUND: Literal["HOST_CREDENTIALS_NOT_FOUND"] = "HOST_CREDENTIALS_NOT_FOUND"
HOST_CREDENTIALS_NOT_SUPPORTED: Literal["HOST_CREDENTIALS_NOT_SUPPORTED"] = "HOST_CREDENTIALS_NOT_SUPPORTED"
HOST_CREDENTIALS_UNAVAILABLE: Literal["HOST_CREDENTIALS_UNAVAILABLE"] = "HOST_CREDENTIALS_UNAVAILABLE"
INTERNAL_ERROR: Literal["INTERNAL_ERROR"] = "INTERNAL_ERROR"
INTERNAL_RATE_LIMITED: Literal["INTERNAL_RATE_LIMITED"] = "INTERNAL_RATE_LIMITED"
INVALID_ARGUMENT: Literal["INVALID_ARGUMENT"] = "INVALID_ARGUMENT"
INVALID_CONFIGURATION: Literal["INVALID_CONFIGURATION"] = "INVALID_CONFIGURATION"
INVALID_STATE: Literal["INVALID_STATE"] = "INVALID_STATE"
LICENSE_EXCEEDED: Literal["LICENSE_EXCEEDED"] = "LICENSE_EXCEEDED"
LICENSE_EXPIRED: Literal["LICENSE_EXPIRED"] = "LICENSE_EXPIRED"
LICENSE_NOT_FOUND: Literal["LICENSE_NOT_FOUND"] = "LICENSE_NOT_FOUND"
LICENSE_NOT_SUPPORTED: Literal["LICENSE_NOT_SUPPORTED"] = "LICENSE_NOT_SUPPORTED"
LOCK_FAILED: Literal["LOCK_FAILED"] = "LOCK_FAILED"
LOCK_TIMEOUT: Literal["LOCK_TIMEOUT"] = "LOCK_TIMEOUT"
LOG_NOT_FOUND: Literal["LOG_NOT_FOUND"] = "LOG_NOT_FOUND"
LOG_NOT_SUPPORTED: Literal["LOG_NOT_SUPPORTED"] = "LOG_NOT_SUPPORTED"
LOG_RETENTION_NOT_SUPPORTED: Literal["LOG_RETENTION_NOT_SUPPORTED"] = "LOG_RETENTION_NOT_SUPPORTED"
MAINTENANCE: Literal["MAINTENANCE"] = "MAINTENANCE"
MAINTENANCE_NOT_SCHEDULED: Literal["MAINTENANCE_NOT_SCHEDULED"] = "MAINTENANCE_NOT_SCHEDULED"
MAINTENANCE_SCHEDULED: Literal["MAINTENANCE_SCHEDULED"] = "MAINTENANCE_SCHEDULED"
MODEL_APPROVAL_BLOCKED: Literal["MODEL_APPROVAL_BLOCKED"] = "MODEL_APPROVAL_BLOCKED"
MODEL_APPROVAL_REQUIRED: Literal["MODEL_APPROVAL_REQUIRED"] = "MODEL_APPROVAL_REQUIRED"
MODEL_APPROVAL_REVOKED: Literal["MODEL_APPROVAL_REVOKED"] = "MODEL_APPROVAL_REVOKED"
MODEL_DISABLED: Literal["MODEL_DISABLED"] = "MODEL_DISABLED"
MODEL_NOT_FOUND: Literal["MODEL_NOT_FOUND"] = "MODEL_NOT_FOUND"
MODEL_NOT_SUPPORTED: Literal["MODEL_NOT_SUPPORTED"] = "MODEL_NOT_SUPPORTED"
MODEL_UPSTREAM_AUTH_FAILED: Literal["MODEL_UPSTREAM_AUTH_FAILED"] = "MODEL_UPSTREAM_AUTH_FAILED"
MODEL_UPSTREAM_AUTH_REQUIRED: Literal["MODEL_UPSTREAM_AUTH_REQUIRED"] = "MODEL_UPSTREAM_AUTH_REQUIRED"
MODEL_UPSTREAM_NOT_AVAILABLE: Literal["MODEL_UPSTREAM_NOT_AVAILABLE"] = "MODEL_UPSTREAM_NOT_AVAILABLE"
MODEL_UPSTREAM_RATE_LIMITED: Literal["MODEL_UPSTREAM_RATE_LIMITED"] = "MODEL_UPSTREAM_RATE_LIMITED"
MODEL_UPSTREAM_UNREACHABLE: Literal["MODEL_UPSTREAM_UNREACHABLE"] = "MODEL_UPSTREAM_UNREACHABLE"
NEEDS_PARENT_SESSION: Literal["NEEDS_PARENT_SESSION"] = "NEEDS_PARENT_SESSION"
NOT_ENOUGH_CAPACITY: Literal["NOT_ENOUGH_CAPACITY"] = "NOT_ENOUGH_CAPACITY"
NOT_FOUND: Literal["NOT_FOUND"] = "NOT_FOUND"
NOT_SUPPORTED: Literal["NOT_SUPPORTED"] = "NOT_SUPPORTED"
NODE_CONNECT_BLOCKED: Literal["NODE_CONNECT_BLOCKED"] = "NODE_CONNECT_BLOCKED"
NODE_CONNECT_FAILED: Literal["NODE_CONNECT_FAILED"] = "NODE_CONNECT_FAILED"
NODE_CONNECT_NOT_FOUND: Literal["NODE_CONNECT_NOT_FOUND"] = "NODE_CONNECT_NOT_FOUND"
NODE_CONNECT_REJECTED: Literal["NODE_CONNECT_REJECTED"] = "NODE_CONNECT_REJECTED"
NODE_CONNECT_TIMEOUT: Literal["NODE_CONNECT_TIMEOUT"] = "NODE_CONNECT_TIMEOUT"
NODE_CONNECT_UNSUPPORTED_PROTOCOL: Literal["NODE_CONNECT_UNSUPPORTED_PROTOCOL"] = "NODE_CONNECT_UNSUPPORTED_PROTOCOL"
NODE_DISABLED: Literal["NODE_DISABLED"] = "NODE_DISABLED"
NODE_GATEWAY_COMM_ERROR: Literal["NODE_GATEWAY_COMM_ERROR"] = "NODE_GATEWAY_COMM_ERROR"
NODE_GATEWAY_COMM_TIMED_OUT: Literal["NODE_GATEWAY_COMM_TIMED_OUT"] = "NODE_GATEWAY_COMM_TIMED_OUT"
NODE_GATEWAY_PROTOCOL_MISMATCH: Literal["NODE_GATEWAY_PROTOCOL_MISMATCH"] = "NODE_GATEWAY_PROTOCOL_MISMATCH"
NODE_GATEWAY_UNREACHABLE: Literal["NODE_GATEWAY_UNREACHABLE"] = "NODE_GATEWAY_UNREACHABLE"
NODE_NOT_FOUND: Literal["NODE_NOT_FOUND"] = "NODE_NOT_FOUND"
NODE_NOT_SUPPORTED: Literal["NODE_NOT_SUPPORTED"] = "NODE_NOT_SUPPORTED"
NODE_RATE_LIMITED: Literal["NODE_RATE_LIMITED"] = "NODE_RATE_LIMITED"
NODE_REVOKED: Literal["NODE_REVOKED"] = "NODE_REVOKED"
NODE_TEMPORARILY_UNAVAILABLE: Literal["NODE_TEMPORARILY_UNAVAILABLE"] = "NODE_TEMPORARILY_UNAVAILABLE"
NOT_IMPLEMENTED: Literal["NOT_IMPLEMENTED"] = "NOT_IMPLEMENTED"
NOT_SUPPORTED_YET: Literal["NOT_SUPPORTED_YET"] = "NOT_SUPPORTED_YET"
PARENT_SESSION_NOT_FOUND: Literal["PARENT_SESSION_NOT_FOUND"] = "PARENT_SESSION_NOT_FOUND"
PARENT_SESSION_NOT_SUPPORTED: Literal["PARENT_SESSION_NOT_SUPPORTED"] = "PARENT_SESSION_NOT_SUPPORTED"
PERMISSION_DENIED: Literal["PERMISSION_DENIED"] = "PERMISSION_DENIED"
PLUGIN_APPROVAL_BLOCKED: Literal["PLUGIN_APPROVAL_BLOCKED"] = "PLUGIN_APPROVAL_BLOCKED"
PLUGIN_APPROVAL_REQUIRED: Literal["PLUGIN_APPROVAL_REQUIRED"] = "PLUGIN_APPROVAL_REQUIRED"
PLUGIN_APPROVAL_REVOKED: Literal["PLUGIN_APPROVAL_REVOKED"] = "PLUGIN_APPROVAL_REVOKED"
PLUGIN_BLOCKED: Literal["PLUGIN_BLOCKED"] = "PLUGIN_BLOCKED"
PLUGIN_NOT_FOUND: Literal["PLUGIN_NOT_FOUND"] = "PLUGIN_NOT_FOUND"
PLUGIN_NOT_SUPPORTED: Literal["PLUGIN_NOT_SUPPORTED"] = "PLUGIN_NOT_SUPPORTED"
PLUGIN_UNSAFE: Literal["PLUGIN_UNSAFE"] = "PLUGIN_UNSAFE"
PROBE_DISABLED: Literal["PROBE_DISABLED"] = "PROBE_DISABLED"
PROBE_NOT_SUPPORTED: Literal["PROBE_NOT_SUPPORTED"] = "PROBE_NOT_SUPPORTED"
PROTOCOL_UPGRADE_FAILED: Literal["PROTOCOL_UPGRADE_FAILED"] = "PROTOCOL_UPGRADE_FAILED"
PROTOCOL_UPGRADE_REQUIRED: Literal["PROTOCOL_UPGRADE_REQUIRED"] = "PROTOCOL_UPGRADE_REQUIRED"
PROTOCOL_VERSION_MISMATCH: Literal["PROTOCOL_VERSION_MISMATCH"] = "PROTOCOL_VERSION_MISMATCH"
PROTOCOL_VERSION_TOO_OLD: Literal["PROTOCOL_VERSION_TOO_OLD"] = "PROTOCOL_VERSION_TOO_OLD"
PUSH_FAILED: Literal["PUSH_FAILED"] = "PUSH_FAILED"
PUSH_NOT_SUPPORTED: Literal["PUSH_NOT_SUPPORTED"] = "PUSH_NOT_SUPPORTED"
PUSH_QUOTA_EXCEEDED: Literal["PUSH_QUOTA_EXCEEDED"] = "PUSH_QUOTA_EXCEEDED"
PUSH_UNSUPPORTED_CONTENT_TYPE: Literal["PUSH_UNSUPPORTED_CONTENT_TYPE"] = "PUSH_UNSUPPORTED_CONTENT_TYPE"
RATE_LIMITED: Literal["RATE_LIMITED"] = "RATE_LIMITED"
RESOURCE_EXHAUSTED: Literal["RESOURCE_EXHAUSTED"] = "RESOURCE_EXHAUSTED"
RESTART_REQUIRED: Literal["RESTART_REQUIRED"] = "RESTART_REQUIRED"
RUN_BLOCKED: Literal["RUN_BLOCKED"] = "RUN_BLOCKED"
RUN_CANCELLED: Literal["RUN_CANCELLED"] = "RUN_CANCELLED"
RUN_NOT_FOUND: Literal["RUN_NOT_FOUND"] = "RUN_NOT_FOUND"
RUN_NOT_PENDING: Literal["RUN_NOT_PENDING"] = "RUN_NOT_PENDING"
RUN_NOT_SUPPORTED: Literal["RUN_NOT_SUPPORTED"] = "RUN_NOT_SUPPORTED"
RUN_REVOKED: Literal["RUN_REVOKED"] = "RUN_REVOKED"
RUN_TIMEOUT: Literal["RUN_TIMEOUT"] = "RUN_TIMEOUT"
RUN_UNSUPPORTED_STATE: Literal["RUN_UNSUPPORTED_STATE"] = "RUN_UNSUPPORTED_STATE"
SECRET_NOT_FOUND: Literal["SECRET_NOT_FOUND"] = "SECRET_NOT_FOUND"
SECRET_READ_DENIED: Literal["SECRET_READ_DENIED"] = "SECRET_READ_DENIED"
SECRET_REF_NOT_FOUND: Literal["SECRET_REF_NOT_FOUND"] = "SECRET_REF_NOT_FOUND"
SECRET_REF_READ_DENIED: Literal["SECRET_REF_READ_DENIED"] = "SECRET_REF_READ_DENIED"
SESSION_ALREADY_EXISTS: Literal["SESSION_ALREADY_EXISTS"] = "SESSION_ALREADY_EXISTS"
SESSION_CLOSED: Literal["SESSION_CLOSED"] = "SESSION_CLOSED"
SESSION_NOT_FOUND: Literal["SESSION_NOT_FOUND"] = "SESSION_NOT_FOUND"
SESSION_NOT_SUPPORTED: Literal["SESSION_NOT_SUPPORTED"] = "SESSION_NOT_SUPPORTED"
SESSION_RESTORE_FAILED: Literal["SESSION_RESTORE_FAILED"] = "SESSION_RESTORE_FAILED"
SESSION_TYPE_NOT_SUPPORTED: Literal["SESSION_TYPE_NOT_SUPPORTED"] = "SESSION_TYPE_NOT_SUPPORTED"
SESSION_VERSION_INCOMPATIBLE: Literal["SESSION_VERSION_INCOMPATIBLE"] = "SESSION_VERSION_INCOMPATIBLE"
SNAPSHOT_NOT_FOUND: Literal["SNAPSHOT_NOT_FOUND"] = "SNAPSHOT_NOT_FOUND"
STATE_VERSION_OUT_OF_DATE: Literal["STATE_VERSION_OUT_OF_DATE"] = "STATE_VERSION_OUT_OF_DATE"
STREAMS_NOT_SUPPORTED: Literal["STREAMS_NOT_SUPPORTED"] = "STREAMS_NOT_SUPPORTED"
STUN_NOT_AVAILABLE: Literal["STUN_NOT_AVAILABLE"] = "STUN_NOT_AVAILABLE"
STUN_QUERY_FAILED: Literal["STUN_QUERY_FAILED"] = "STUN_QUERY_FAILED"
STUN_QUERY_TIMEOUT: Literal["STUN_QUERY_TIMEOUT"] = "STUN_QUERY_TIMEOUT"
STUN_REQUIRED: Literal["STUN_REQUIRED"] = "STUN_REQUIRED"
STUN_SERVER_NOT_FOUND: Literal["STUN_SERVER_NOT_FOUND"] = "STUN_SERVER_NOT_FOUND"
STUN_SERVER_UNREACHABLE: Literal["STUN_SERVER_UNREACHABLE"] = "STUN_SERVER_UNREACHABLE"
STUN_UNAVAILABLE: Literal["STUN_UNAVAILABLE"] = "STUN_UNAVAILABLE"
STUN_UPGRADE_FAILED: Literal["STUN_UPGRADE_FAILED"] = "STUN_UPGRADE_FAILED"
STUN_UPGRADE_REQUIRED: Literal["STUN_UPGRADE_REQUIRED"] = "STUN_UPGRADE_REQUIRED"
STUN_VERSION_MISMATCH: Literal["STUN_VERSION_MISMATCH"] = "STUN_VERSION_MISMATCH"
STUN_VERSION_NOT_SUPPORTED: Literal["STUN_VERSION_NOT_SUPPORTED"] = "STUN_VERSION_NOT_SUPPORTED"
STUN_VERSION_TOO_OLD: Literal["STUN_VERSION_TOO_OLD"] = "STUN_VERSION_TOO_OLD"
STUN_VIOLATION: Literal["STUN_VIOLATION"] = "STUN_VIOLATION"
SUBMIT_BLOCKED: Literal["SUBMIT_BLOCKED"] = "SUBMIT_BLOCKED"
SUBMIT_FAILED: Literal["SUBMIT_FAILED"] = "SUBMIT_FAILED"
SUBMIT_NOT_SUPPORTED: Literal["SUBMIT_NOT_SUPPORTED"] = "SUBMIT_NOT_SUPPORTED"
SUBMIT_TIMEOUT: Literal["SUBMIT_TIMEOUT"] = "SUBMIT_TIMEOUT"
TASK_ALREADY_EXISTS: Literal["TASK_ALREADY_EXISTS"] = "TASK_ALREADY_EXISTS"
TASK_ASSIGNMENT_BLOCKED: Literal["TASK_ASSIGNMENT_BLOCKED"] = "TASK_ASSIGNMENT_BLOCKED"
TASK_NOT_FOUND: Literal["TASK_NOT_FOUND"] = "TASK_NOT_FOUND"
TASK_NOT_READY: Literal["TASK_NOT_READY"] = "TASK_NOT_READY"
TASK_NOT_SUPPORTED: Literal["TASK_NOT_SUPPORTED"] = "TASK_NOT_SUPPORTED"
TASK_PARENT_NOT_FOUND: Literal["TASK_PARENT_NOT_FOUND"] = "TASK_PARENT_NOT_FOUND"
TASK_STATE_NOT_ALLOWED: Literal["TASK_STATE_NOT_ALLOWED"] = "TASK_STATE_NOT_ALLOWED"
TASK_STATE_NOT_SUPPORTED: Literal["TASK_STATE_NOT_SUPPORTED"] = "TASK_STATE_NOT_SUPPORTED"
TASK_SUBTASK_BLOCKED: Literal["TASK_SUBTASK_BLOCKED"] = "TASK_SUBTASK_BLOCKED"
TASK_UPSTREAM_AUTH_FAILED: Literal["TASK_UPSTREAM_AUTH_FAILED"] = "TASK_UPSTREAM_AUTH_FAILED"
TASK_UPSTREAM_AUTH_REQUIRED: Literal["TASK_UPSTREAM_AUTH_REQUIRED"] = "TASK_UPSTREAM_AUTH_REQUIRED"
TASK_UPSTREAM_NOT_AVAILABLE: Literal["TASK_UPSTREAM_NOT_AVAILABLE"] = "TASK_UPSTREAM_NOT_AVAILABLE"
TASK_UPSTREAM_RATE_LIMITED: Literal["TASK_UPSTREAM_RATE_LIMITED"] = "TASK_UPSTREAM_RATE_LIMITED"
TASK_UPSTREAM_UNREACHABLE: Literal["TASK_UPSTREAM_UNREACHABLE"] = "TASK_UPSTREAM_UNREACHABLE"
TOOL_BLOCKED: Literal["TOOL_BLOCKED"] = "TOOL_BLOCKED"
TOOL_NOT_FOUND: Literal["TOOL_NOT_FOUND"] = "TOOL_NOT_FOUND"
TOOL_NOT_SUPPORTED: Literal["TOOL_NOT_SUPPORTED"] = "TOOL_NOT_SUPPORTED"
TOOL_REVOKED: Literal["TOOL_REVOKED"] = "TOOL_REVOKED"
TOOL_TRUST_NOT_SUPPORTED: Literal["TOOL_TRUST_NOT_SUPPORTED"] = "TOOL_TRUST_NOT_SUPPORTED"
TOOL_TRUST_REVOKED: Literal["TOOL_TRUST_REVOKED"] = "TOOL_TRUST_REVOKED"
TRANSFORM_FAILED: Literal["TRANSFORM_FAILED"] = "TRANSFORM_FAILED"
UPGRADE_REQUIRED: Literal["UPGRADE_REQUIRED"] = "UPGRADE_REQUIRED"
UPSTREAM_AUTH_FAILED: Literal["UPSTREAM_AUTH_FAILED"] = "UPSTREAM_AUTH_FAILED"
UPSTREAM_AUTH_REQUIRED: Literal["UPSTREAM_AUTH_REQUIRED"] = "UPSTREAM_AUTH_REQUIRED"
UPSTREAM_DISABLED: Literal["UPSTREAM_DISABLED"] = "UPSTREAM_DISABLED"
UPSTREAM_NOT_AVAILABLE: Literal["UPSTREAM_NOT_AVAILABLE"] = "UPSTREAM_NOT_AVAILABLE"
UPSTREAM_RATE_LIMITED: Literal["UPSTREAM_RATE_LIMITED"] = "UPSTREAM_RATE_LIMITED"
UPSTREAM_UNREACHABLE: Literal["UPSTREAM_UNREACHABLE"] = "UPSTREAM_UNREACHABLE"
VALIDATION_FAILED: Literal["VALIDATION_FAILED"] = "VALIDATION_FAILED"
VCS_UPLOAD_UNAVAILABLE: Literal["VCS_UPLOAD_UNAVAILABLE"] = "VCS_UPLOAD_UNAVAILABLE"

ERROR_CODES: Final[tuple] = (
    AGENT_RUN_BLOCKED,
    AGENT_VERSION_OUT_OF_DATE,
    APPROVAL_LOCKED,
    APPROVAL_LOCK_TIMEOUT,
    APPROVAL_REJECTED,
    APPROVAL_REQUIRED,
    APPROVAL_REVOKED,
    APPROVAL_RUN_MISMATCH,
    APPROVAL_RUN_NOT_FOUND,
    APPROVAL_RUN_NOT_PENDING,
    ARTIFACT_IN_USE_BY_RUN,
    ARTIFACT_NOT_FOUND,
    ARTIFACT_PUSH_FAILED,
    ARTIFACT_PUSH_UNAUTHORIZED,
    ARTIFACT_UPLOAD_UNAVAILABLE,
    AUTH_REQUIRED,
    AUTH_UNAUTHORIZED,
    AWARD_REJECTED,
    AWARD_REQUIRED,
    AWARD_REVOKED,
    AWARD_RUN_MISMATCH,
    AWARD_RUN_NOT_FOUND,
    AWARD_RUN_NOT_PENDING,
    BAD_REQUEST,
    CA_CERT_EXPIRED,
    CA_CERT_UNTRUSTED,
    CA_CERT_VALIDATION_FAILED,
    CAPABILITY_DISABLED,
    CAPABILITY_NOT_SUPPORTED,
    CA_CERT_MISSING,
    CA_CERT_REQUIRED,
    CA_CERT_VALIDATION_UNAVAILABLE,
    CHAT_SESSION_CLOSED,
    CHAT_SESSION_NOT_FOUND,
    CLEANUP_FAILED,
    COMMIT_BLOCKED,
    CONFIG_PARSE_FAILED,
    CONFIG_SCHEMA_INVALID,
    CONFLICT,
    CONNECT_BLOCKED,
    CONNECT_FAILED,
    CONNECT_NOT_FOUND,
    CONNECT_REJECTED,
    CONNECT_REQUIRED,
    CONNECT_TIMEOUT,
    CONNECT_UNAUTHORIZED,
    CONNECT_UNAVAILABLE,
    CRON_DISABLED,
    CRON_NOT_FOUND,
    CRON_NOT_SUPPORTED,
    CRON_PARSE_FAILED,
    DEADLINE_EXCEEDED,
    DEBUG_SESSION_NOT_FOUND,
    DEBUG_SESSION_NOT_SUPPORTED,
    DEVICE_PAIR_FAILED,
    DEVICE_PAIR_NOT_SUPPORTED,
    DEVICE_PAIR_REVOKED,
    DEVICE_REVOKED,
    DEVICE_TRUST_FAILED,
    DEVICE_TRUST_NOT_SUPPORTED,
    DEVICE_TRUST_REVOKED,
    DIRECTORY_IN_USE_BY_RUN,
    DIRECTORY_NOT_FOUND,
    DIRECTORY_UPLOAD_UNAVAILABLE,
    DISCONNECT_REQUIRED,
    DOES_NOT_EXIST,
    DOWNSTREAM_DEPENDENCY_FAILED,
    DOWNSTREAM_DEPENDENCY_UNAVAILABLE,
    DOWNSTREAM_PROTOCOL_NEGOTIATION_FAILED,
    DOWNSTREAM_PROTOCOL_VERSION_UNSUPPORTED,
    DOWNSTREAM_QUOTA_EXCEEDED,
    DOWNSTREAM_RATE_LIMITED,
    DOWNSTREAM_UNREACHABLE,
    DOWNSTREAM_UPSTREAM_AUTH_FAILED,
    DOWNSTREAM_UPSTREAM_AUTH_REQUIRED,
    ELEVATION_BLOCKED,
    ELEVATION_REQUIRED,
    ELEVATION_REVOKED,
    ENVIRONMENT_NOT_FOUND,
    EXEC_APPROVAL_BLOCKED,
    EXEC_APPROVAL_REQUIRED,
    EXEC_APPROVAL_REVOKED,
    EXEC_BLOCKED,
    EXEC_DISABLED,
    EXEC_NOT_SUPPORTED,
    EXEC_REQUIRED,
    EXEC_REVOKED,
    GATEWAY_BUSY,
    GATEWAY_NOT_AVAILABLE,
    GATEWAY_NOT_FOUND,
    GATEWAY_SHUTDOWN,
    GATEWAY_TIMEOUT,
    GATEWAY_VERSION_MISMATCH,
    HOST_CREDENTIALS_NOT_FOUND,
    HOST_CREDENTIALS_NOT_SUPPORTED,
    HOST_CREDENTIALS_UNAVAILABLE,
    INTERNAL_ERROR,
    INTERNAL_RATE_LIMITED,
    INVALID_ARGUMENT,
    INVALID_CONFIGURATION,
    INVALID_STATE,
    LICENSE_EXCEEDED,
    LICENSE_EXPIRED,
    LICENSE_NOT_FOUND,
    LICENSE_NOT_SUPPORTED,
    LOCK_FAILED,
    LOCK_TIMEOUT,
    LOG_NOT_FOUND,
    LOG_NOT_SUPPORTED,
    LOG_RETENTION_NOT_SUPPORTED,
    MAINTENANCE,
    MAINTENANCE_NOT_SCHEDULED,
    MAINTENANCE_SCHEDULED,
    MODEL_APPROVAL_BLOCKED,
    MODEL_APPROVAL_REQUIRED,
    MODEL_APPROVAL_REVOKED,
    MODEL_DISABLED,
    MODEL_NOT_FOUND,
    MODEL_NOT_SUPPORTED,
    MODEL_UPSTREAM_AUTH_FAILED,
    MODEL_UPSTREAM_AUTH_REQUIRED,
    MODEL_UPSTREAM_NOT_AVAILABLE,
    MODEL_UPSTREAM_RATE_LIMITED,
    MODEL_UPSTREAM_UNREACHABLE,
    NEEDS_PARENT_SESSION,
    NOT_ENOUGH_CAPACITY,
    NOT_FOUND,
    NOT_SUPPORTED,
    NODE_CONNECT_BLOCKED,
    NODE_CONNECT_FAILED,
    NODE_CONNECT_NOT_FOUND,
    NODE_CONNECT_REJECTED,
    NODE_CONNECT_TIMEOUT,
    NODE_CONNECT_UNSUPPORTED_PROTOCOL,
    NODE_DISABLED,
    NODE_GATEWAY_COMM_ERROR,
    NODE_GATEWAY_COMM_TIMED_OUT,
    NODE_GATEWAY_PROTOCOL_MISMATCH,
    NODE_GATEWAY_UNREACHABLE,
    NODE_NOT_FOUND,
    NODE_NOT_SUPPORTED,
    NODE_RATE_LIMITED,
    NODE_REVOKED,
    NODE_TEMPORARILY_UNAVAILABLE,
    NOT_IMPLEMENTED,
    NOT_SUPPORTED_YET,
    PARENT_SESSION_NOT_FOUND,
    PARENT_SESSION_NOT_SUPPORTED,
    PERMISSION_DENIED,
    PLUGIN_APPROVAL_BLOCKED,
    PLUGIN_APPROVAL_REQUIRED,
    PLUGIN_APPROVAL_REVOKED,
    PLUGIN_BLOCKED,
    PLUGIN_NOT_FOUND,
    PLUGIN_NOT_SUPPORTED,
    PLUGIN_UNSAFE,
    PROBE_DISABLED,
    PROBE_NOT_SUPPORTED,
    PROTOCOL_UPGRADE_FAILED,
    PROTOCOL_UPGRADE_REQUIRED,
    PROTOCOL_VERSION_MISMATCH,
    PROTOCOL_VERSION_TOO_OLD,
    PUSH_FAILED,
    PUSH_NOT_SUPPORTED,
    PUSH_QUOTA_EXCEEDED,
    PUSH_UNSUPPORTED_CONTENT_TYPE,
    RATE_LIMITED,
    RESOURCE_EXHAUSTED,
    RESTART_REQUIRED,
    RUN_BLOCKED,
    RUN_CANCELLED,
    RUN_NOT_FOUND,
    RUN_NOT_PENDING,
    RUN_NOT_SUPPORTED,
    RUN_REVOKED,
    RUN_TIMEOUT,
    RUN_UNSUPPORTED_STATE,
    SECRET_NOT_FOUND,
    SECRET_READ_DENIED,
    SECRET_REF_NOT_FOUND,
    SECRET_REF_READ_DENIED,
    SESSION_ALREADY_EXISTS,
    SESSION_CLOSED,
    SESSION_NOT_FOUND,
    SESSION_NOT_SUPPORTED,
    SESSION_RESTORE_FAILED,
    SESSION_TYPE_NOT_SUPPORTED,
    SESSION_VERSION_INCOMPATIBLE,
    SNAPSHOT_NOT_FOUND,
    STATE_VERSION_OUT_OF_DATE,
    STREAMS_NOT_SUPPORTED,
    STUN_NOT_AVAILABLE,
    STUN_QUERY_FAILED,
    STUN_QUERY_TIMEOUT,
    STUN_REQUIRED,
    STUN_SERVER_NOT_FOUND,
    STUN_SERVER_UNREACHABLE,
    STUN_UNAVAILABLE,
    STUN_UPGRADE_FAILED,
    STUN_UPGRADE_REQUIRED,
    STUN_VERSION_MISMATCH,
    STUN_VERSION_NOT_SUPPORTED,
    STUN_VERSION_TOO_OLD,
    STUN_VIOLATION,
    SUBMIT_BLOCKED,
    SUBMIT_FAILED,
    SUBMIT_NOT_SUPPORTED,
    SUBMIT_TIMEOUT,
    TASK_ALREADY_EXISTS,
    TASK_ASSIGNMENT_BLOCKED,
    TASK_NOT_FOUND,
    TASK_NOT_READY,
    TASK_NOT_SUPPORTED,
    TASK_PARENT_NOT_FOUND,
    TASK_STATE_NOT_ALLOWED,
    TASK_STATE_NOT_SUPPORTED,
    TASK_SUBTASK_BLOCKED,
    TASK_UPSTREAM_AUTH_FAILED,
    TASK_UPSTREAM_AUTH_REQUIRED,
    TASK_UPSTREAM_NOT_AVAILABLE,
    TASK_UPSTREAM_RATE_LIMITED,
    TASK_UPSTREAM_UNREACHABLE,
    TOOL_BLOCKED,
    TOOL_NOT_FOUND,
    TOOL_NOT_SUPPORTED,
    TOOL_REVOKED,
    TOOL_TRUST_NOT_SUPPORTED,
    TOOL_TRUST_REVOKED,
    TRANSFORM_FAILED,
    UPGRADE_REQUIRED,
    UPSTREAM_AUTH_FAILED,
    UPSTREAM_AUTH_REQUIRED,
    UPSTREAM_DISABLED,
    UPSTREAM_NOT_AVAILABLE,
    UPSTREAM_RATE_LIMITED,
    UPSTREAM_UNREACHABLE,
    VALIDATION_FAILED,
    VCS_UPLOAD_UNAVAILABLE,
)

SCHEMA_ERROR_CODES: Final[tuple] = ERROR_CODES

ErrorCode = Literal[
    "AGENT_RUN_BLOCKED",
    "AGENT_VERSION_OUT_OF_DATE",
    "APPROVAL_LOCKED",
    "APPROVAL_LOCK_TIMEOUT",
    "APPROVAL_REJECTED",
    "APPROVAL_REQUIRED",
    "APPROVAL_REVOKED",
    "APPROVAL_RUN_MISMATCH",
    "APPROVAL_RUN_NOT_FOUND",
    "APPROVAL_RUN_NOT_PENDING",
    "ARTIFACT_IN_USE_BY_RUN",
    "ARTIFACT_NOT_FOUND",
    "ARTIFACT_PUSH_FAILED",
    "ARTIFACT_PUSH_UNAUTHORIZED",
    "ARTIFACT_UPLOAD_UNAVAILABLE",
    "AUTH_REQUIRED",
    "AUTH_UNAUTHORIZED",
    "AWARD_REJECTED",
    "AWARD_REQUIRED",
    "AWARD_REVOKED",
    "AWARD_RUN_MISMATCH",
    "AWARD_RUN_NOT_FOUND",
    "AWARD_RUN_NOT_PENDING",
    "BAD_REQUEST",
    "CA_CERT_EXPIRED",
    "CA_CERT_UNTRUSTED",
    "CA_CERT_VALIDATION_FAILED",
    "CAPABILITY_DISABLED",
    "CAPABILITY_NOT_SUPPORTED",
    "CA_CERT_MISSING",
    "CA_CERT_REQUIRED",
    "CA_CERT_VALIDATION_UNAVAILABLE",
    "CHAT_SESSION_CLOSED",
    "CHAT_SESSION_NOT_FOUND",
    "CLEANUP_FAILED",
    "COMMIT_BLOCKED",
    "CONFIG_PARSE_FAILED",
    "CONFIG_SCHEMA_INVALID",
    "CONFLICT",
    "CONNECT_BLOCKED",
    "CONNECT_FAILED",
    "CONNECT_NOT_FOUND",
    "CONNECT_REJECTED",
    "CONNECT_REQUIRED",
    "CONNECT_TIMEOUT",
    "CONNECT_UNAUTHORIZED",
    "CONNECT_UNAVAILABLE",
    "CRON_DISABLED",
    "CRON_NOT_FOUND",
    "CRON_NOT_SUPPORTED",
    "CRON_PARSE_FAILED",
    "DEADLINE_EXCEEDED",
    "DEBUG_SESSION_NOT_FOUND",
    "DEBUG_SESSION_NOT_SUPPORTED",
    "DEVICE_PAIR_FAILED",
    "DEVICE_PAIR_NOT_SUPPORTED",
    "DEVICE_PAIR_REVOKED",
    "DEVICE_REVOKED",
    "DEVICE_TRUST_FAILED",
    "DEVICE_TRUST_NOT_SUPPORTED",
    "DEVICE_TRUST_REVOKED",
    "DIRECTORY_IN_USE_BY_RUN",
    "DIRECTORY_NOT_FOUND",
    "DIRECTORY_UPLOAD_UNAVAILABLE",
    "DISCONNECT_REQUIRED",
    "DOES_NOT_EXIST",
    "DOWNSTREAM_DEPENDENCY_FAILED",
    "DOWNSTREAM_DEPENDENCY_UNAVAILABLE",
    "DOWNSTREAM_PROTOCOL_NEGOTIATION_FAILED",
    "DOWNSTREAM_PROTOCOL_VERSION_UNSUPPORTED",
    "DOWNSTREAM_QUOTA_EXCEEDED",
    "DOWNSTREAM_RATE_LIMITED",
    "DOWNSTREAM_UNREACHABLE",
    "DOWNSTREAM_UPSTREAM_AUTH_FAILED",
    "DOWNSTREAM_UPSTREAM_AUTH_REQUIRED",
    "ELEVATION_BLOCKED",
    "ELEVATION_REQUIRED",
    "ELEVATION_REVOKED",
    "ENVIRONMENT_NOT_FOUND",
    "EXEC_APPROVAL_BLOCKED",
    "EXEC_APPROVAL_REQUIRED",
    "EXEC_APPROVAL_REVOKED",
    "EXEC_BLOCKED",
    "EXEC_DISABLED",
    "EXEC_NOT_SUPPORTED",
    "EXEC_REQUIRED",
    "EXEC_REVOKED",
    "GATEWAY_BUSY",
    "GATEWAY_NOT_AVAILABLE",
    "GATEWAY_NOT_FOUND",
    "GATEWAY_SHUTDOWN",
    "GATEWAY_TIMEOUT",
    "GATEWAY_VERSION_MISMATCH",
    "HOST_CREDENTIALS_NOT_FOUND",
    "HOST_CREDENTIALS_NOT_SUPPORTED",
    "HOST_CREDENTIALS_UNAVAILABLE",
    "INTERNAL_ERROR",
    "INTERNAL_RATE_LIMITED",
    "INVALID_ARGUMENT",
    "INVALID_CONFIGURATION",
    "INVALID_STATE",
    "LICENSE_EXCEEDED",
    "LICENSE_EXPIRED",
    "LICENSE_NOT_FOUND",
    "LICENSE_NOT_SUPPORTED",
    "LOCK_FAILED",
    "LOCK_TIMEOUT",
    "LOG_NOT_FOUND",
    "LOG_NOT_SUPPORTED",
    "LOG_RETENTION_NOT_SUPPORTED",
    "MAINTENANCE",
    "MAINTENANCE_NOT_SCHEDULED",
    "MAINTENANCE_SCHEDULED",
    "MODEL_APPROVAL_BLOCKED",
    "MODEL_APPROVAL_REQUIRED",
    "MODEL_APPROVAL_REVOKED",
    "MODEL_DISABLED",
    "MODEL_NOT_FOUND",
    "MODEL_NOT_SUPPORTED",
    "MODEL_UPSTREAM_AUTH_FAILED",
    "MODEL_UPSTREAM_AUTH_REQUIRED",
    "MODEL_UPSTREAM_NOT_AVAILABLE",
    "MODEL_UPSTREAM_RATE_LIMITED",
    "MODEL_UPSTREAM_UNREACHABLE",
    "NEEDS_PARENT_SESSION",
    "NOT_ENOUGH_CAPACITY",
    "NOT_FOUND",
    "NOT_SUPPORTED",
    "NODE_CONNECT_BLOCKED",
    "NODE_CONNECT_FAILED",
    "NODE_CONNECT_NOT_FOUND",
    "NODE_CONNECT_REJECTED",
    "NODE_CONNECT_TIMEOUT",
    "NODE_CONNECT_UNSUPPORTED_PROTOCOL",
    "NODE_DISABLED",
    "NODE_GATEWAY_COMM_ERROR",
    "NODE_GATEWAY_COMM_TIMED_OUT",
    "NODE_GATEWAY_PROTOCOL_MISMATCH",
    "NODE_GATEWAY_UNREACHABLE",
    "NODE_NOT_FOUND",
    "NODE_NOT_SUPPORTED",
    "NODE_RATE_LIMITED",
    "NODE_REVOKED",
    "NODE_TEMPORARILY_UNAVAILABLE",
    "NOT_IMPLEMENTED",
    "NOT_SUPPORTED_YET",
    "PARENT_SESSION_NOT_FOUND",
    "PARENT_SESSION_NOT_SUPPORTED",
    "PERMISSION_DENIED",
    "PLUGIN_APPROVAL_BLOCKED",
    "PLUGIN_APPROVAL_REQUIRED",
    "PLUGIN_APPROVAL_REVOKED",
    "PLUGIN_BLOCKED",
    "PLUGIN_NOT_FOUND",
    "PLUGIN_NOT_SUPPORTED",
    "PLUGIN_UNSAFE",
    "PROBE_DISABLED",
    "PROBE_NOT_SUPPORTED",
    "PROTOCOL_UPGRADE_FAILED",
    "PROTOCOL_UPGRADE_REQUIRED",
    "PROTOCOL_VERSION_MISMATCH",
    "PROTOCOL_VERSION_TOO_OLD",
    "PUSH_FAILED",
    "PUSH_NOT_SUPPORTED",
    "PUSH_QUOTA_EXCEEDED",
    "PUSH_UNSUPPORTED_CONTENT_TYPE",
    "RATE_LIMITED",
    "RESOURCE_EXHAUSTED",
    "RESTART_REQUIRED",
    "RUN_BLOCKED",
    "RUN_CANCELLED",
    "RUN_NOT_FOUND",
    "RUN_NOT_PENDING",
    "RUN_NOT_SUPPORTED",
    "RUN_REVOKED",
    "RUN_TIMEOUT",
    "RUN_UNSUPPORTED_STATE",
    "SECRET_NOT_FOUND",
    "SECRET_READ_DENIED",
    "SECRET_REF_NOT_FOUND",
    "SECRET_REF_READ_DENIED",
    "SESSION_ALREADY_EXISTS",
    "SESSION_CLOSED",
    "SESSION_NOT_FOUND",
    "SESSION_NOT_SUPPORTED",
    "SESSION_RESTORE_FAILED",
    "SESSION_TYPE_NOT_SUPPORTED",
    "SESSION_VERSION_INCOMPATIBLE",
    "SNAPSHOT_NOT_FOUND",
    "STATE_VERSION_OUT_OF_DATE",
    "STREAMS_NOT_SUPPORTED",
    "STUN_NOT_AVAILABLE",
    "STUN_QUERY_FAILED",
    "STUN_QUERY_TIMEOUT",
    "STUN_REQUIRED",
    "STUN_SERVER_NOT_FOUND",
    "STUN_SERVER_UNREACHABLE",
    "STUN_UNAVAILABLE",
    "STUN_UPGRADE_FAILED",
    "STUN_UPGRADE_REQUIRED",
    "STUN_VERSION_MISMATCH",
    "STUN_VERSION_NOT_SUPPORTED",
    "STUN_VERSION_TOO_OLD",
    "STUN_VIOLATION",
    "SUBMIT_BLOCKED",
    "SUBMIT_FAILED",
    "SUBMIT_NOT_SUPPORTED",
    "SUBMIT_TIMEOUT",
    "TASK_ALREADY_EXISTS",
    "TASK_ASSIGNMENT_BLOCKED",
    "TASK_NOT_FOUND",
    "TASK_NOT_READY",
    "TASK_NOT_SUPPORTED",
    "TASK_PARENT_NOT_FOUND",
    "TASK_STATE_NOT_ALLOWED",
    "TASK_STATE_NOT_SUPPORTED",
    "TASK_SUBTASK_BLOCKED",
    "TASK_UPSTREAM_AUTH_FAILED",
    "TASK_UPSTREAM_AUTH_REQUIRED",
    "TASK_UPSTREAM_NOT_AVAILABLE",
    "TASK_UPSTREAM_RATE_LIMITED",
    "TASK_UPSTREAM_UNREACHABLE",
    "TOOL_BLOCKED",
    "TOOL_NOT_FOUND",
    "TOOL_NOT_SUPPORTED",
    "TOOL_REVOKED",
    "TOOL_TRUST_NOT_SUPPORTED",
    "TOOL_TRUST_REVOKED",
    "TRANSFORM_FAILED",
    "UPGRADE_REQUIRED",
    "UPSTREAM_AUTH_FAILED",
    "UPSTREAM_AUTH_REQUIRED",
    "UPSTREAM_DISABLED",
    "UPSTREAM_NOT_AVAILABLE",
    "UPSTREAM_RATE_LIMITED",
    "UPSTREAM_UNREACHABLE",
    "VALIDATION_FAILED",
    "VCS_UPLOAD_UNAVAILABLE",
]
