BROWSER_ACT_KINDS = [
    "click",
    "clickCoords",
    "type",
    "press",
    "hover",
    "drag",
    "select",
    "fill",
    "resize",
    "wait",
    "evaluate",
    "close",
]

BROWSER_TOOL_ACTIONS = [
    "doctor",
    "status",
    "start",
    "stop",
    "profiles",
    "tabs",
    "open",
    "focus",
    "close",
    "snapshot",
    "screenshot",
    "navigate",
    "console",
    "pdf",
    "upload",
    "dialog",
    "act",
]

BROWSER_TARGETS = ["sandbox", "host", "node"]
BROWSER_SNAPSHOT_FORMATS = ["aria", "ai"]
BROWSER_SNAPSHOT_MODES = ["efficient"]
BROWSER_SNAPSHOT_REFS = ["role", "aria"]
BROWSER_IMAGE_TYPES = ["png", "jpeg"]

ACT_MAX_VIEWPORT_DIMENSION = 2560

TAB_REFERENCE_DESCRIPTION = (
    "Tab reference. Prefer suggestedTargetId, tabId, or label from tabs output; "
    "raw CDP targetId and unique raw prefixes remain supported for compatibility."
)

_BROWSER_ACT_REQUEST_KEYS = [
    "kind",
    "targetId",
    "ref",
    "doubleClick",
    "button",
    "modifiers",
    "x",
    "y",
    "text",
    "submit",
    "slowly",
    "key",
    "delayMs",
    "startRef",
    "endRef",
    "values",
    "fields",
    "width",
    "height",
    "timeMs",
    "textGone",
    "selector",
    "url",
    "loadState",
    "fn",
    "timeoutMs",
]

_LEGACY_BROWSER_ACT_SHARED_REQUEST_KEYS = {"targetId"}

BrowserActSchema: dict = {
    "type": "object",
    "properties": {
        "kind": {"type": "string", "enum": BROWSER_ACT_KINDS},
        "targetId": {"type": "string", "description": TAB_REFERENCE_DESCRIPTION},
        "ref": {"type": "string"},
        "doubleClick": {"type": "boolean"},
        "button": {"type": "string"},
        "modifiers": {"type": "array", "items": {"type": "string"}},
        "x": {"type": "number"},
        "y": {"type": "number"},
        "text": {"type": "string"},
        "submit": {"type": "boolean"},
        "slowly": {"type": "boolean"},
        "key": {"type": "string"},
        "delayMs": {"type": "integer", "minimum": 0},
        "startRef": {"type": "string"},
        "endRef": {"type": "string"},
        "values": {"type": "array", "items": {"type": "string"}},
        "fields": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
        "width": {"type": "integer", "minimum": 1, "maximum": ACT_MAX_VIEWPORT_DIMENSION},
        "height": {"type": "integer", "minimum": 1, "maximum": ACT_MAX_VIEWPORT_DIMENSION},
        "timeMs": {"type": "integer", "minimum": 0},
        "selector": {"type": "string"},
        "url": {"type": "string"},
        "loadState": {"type": "string"},
        "textGone": {"type": "string"},
        "timeoutMs": {"type": "integer", "minimum": 1},
        "fn": {"type": "string"},
    },
    "required": ["kind"],
}

BrowserToolSchema: dict = {
    "type": "object",
    "properties": {
        "action": {"type": "string", "enum": BROWSER_TOOL_ACTIONS},
        "target": {"type": "string", "enum": BROWSER_TARGETS},
        "node": {"type": "string"},
        "profile": {"type": "string"},
        "targetUrl": {"type": "string"},
        "url": {"type": "string"},
        "targetId": {"type": "string", "description": TAB_REFERENCE_DESCRIPTION},
        "label": {"type": "string"},
        "limit": {"type": "integer", "minimum": 1},
        "maxChars": {"type": "integer", "minimum": 0},
        "mode": {"type": "string", "enum": BROWSER_SNAPSHOT_MODES},
        "snapshotFormat": {"type": "string", "enum": BROWSER_SNAPSHOT_FORMATS},
        "refs": {"type": "string", "enum": BROWSER_SNAPSHOT_REFS},
        "interactive": {"type": "boolean"},
        "compact": {"type": "boolean"},
        "depth": {"type": "integer", "minimum": 0},
        "selector": {"type": "string"},
        "frame": {"type": "string"},
        "labels": {"type": "boolean"},
        "urls": {"type": "boolean"},
        "fullPage": {"type": "boolean"},
        "ref": {"type": "string"},
        "element": {"type": "string"},
        "type": {"type": "string", "enum": BROWSER_IMAGE_TYPES},
        "level": {"type": "string"},
        "paths": {"type": "array", "items": {"type": "string"}},
        "inputRef": {"type": "string"},
        "timeoutMs": {"type": "integer", "minimum": 1},
        "dialogId": {"type": "string"},
        "accept": {"type": "boolean"},
        "promptText": {"type": "string"},
        "kind": {"type": "string", "enum": BROWSER_ACT_KINDS},
        "doubleClick": {"type": "boolean"},
        "button": {"type": "string"},
        "modifiers": {"type": "array", "items": {"type": "string"}},
        "x": {"type": "number"},
        "y": {"type": "number"},
        "text": {"type": "string"},
        "submit": {"type": "boolean"},
        "slowly": {"type": "boolean"},
        "key": {"type": "string"},
        "delayMs": {"type": "integer", "minimum": 0},
        "startRef": {"type": "string"},
        "endRef": {"type": "string"},
        "values": {"type": "array", "items": {"type": "string"}},
        "fields": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
        "width": {"type": "integer", "minimum": 1, "maximum": ACT_MAX_VIEWPORT_DIMENSION},
        "height": {"type": "integer", "minimum": 1, "maximum": ACT_MAX_VIEWPORT_DIMENSION},
        "timeMs": {"type": "integer", "minimum": 0},
        "textGone": {"type": "string"},
        "loadState": {"type": "string"},
        "fn": {"type": "string"},
        "request": BrowserActSchema,
    },
    "required": ["action"],
}
