"""Session extension system for lifecycle events and custom tools."""

from openclaw.agents.sessions.extensions.loader import (
    create_extension_runtime,
    load_extension_from_factory,
    load_extensions,
)
from openclaw.agents.sessions.extensions.runner import (
    ExtensionRunner,
    emit_session_shutdown_event,
)
from openclaw.agents.sessions.extensions.types import (
    RESERVED_KEYBINDINGS_FOR_EXTENSION_CONFLICTS,
    BUILTIN_TOOL_NAMES,
    CompactOptions,
    ContextUsage,
    Extension,
    ExtensionError,
    ExtensionFlag,
    ExtensionShortcut,
    LoadExtensionsResult,
    ProviderConfig,
    ProviderModelConfig,
    RegisteredCommand,
    RegisteredTool,
    SourceInfo,
    ToolDefinition,
    create_synthetic_source_info,
    define_tool,
    is_bash_tool_result,
    is_edit_tool_result,
    is_find_tool_result,
    is_grep_tool_result,
    is_ls_tool_result,
    is_read_tool_result,
    is_tool_call_event_type,
    is_write_tool_result,
    normalize_input_event_result,
)
from openclaw.agents.sessions.extensions.wrapper import (
    wrap_registered_tool,
    wrap_registered_tools,
)

__all__ = [
    "BUILTIN_TOOL_NAMES",
    "CompactOptions",
    "ContextUsage",
    "Extension",
    "ExtensionError",
    "ExtensionFlag",
    "ExtensionRunner",
    "ExtensionShortcut",
    "LoadExtensionsResult",
    "ProviderConfig",
    "ProviderModelConfig",
    "RESERVED_KEYBINDINGS_FOR_EXTENSION_CONFLICTS",
    "RegisteredCommand",
    "RegisteredTool",
    "SourceInfo",
    "ToolDefinition",
    "create_extension_runtime",
    "create_synthetic_source_info",
    "define_tool",
    "emit_session_shutdown_event",
    "is_bash_tool_result",
    "is_edit_tool_result",
    "is_find_tool_result",
    "is_grep_tool_result",
    "is_ls_tool_result",
    "is_read_tool_result",
    "is_tool_call_event_type",
    "is_write_tool_result",
    "load_extension_from_factory",
    "load_extensions",
    "normalize_input_event_result",
    "wrap_registered_tool",
    "wrap_registered_tools",
]
