from dataclasses import dataclass, field
from typing import Optional


@dataclass
class GoogleConfigDefaults:
    google_api_key: Optional[str] = None
    google_project_id: Optional[str] = None
    google_client_id: Optional[str] = None
    google_client_secret: Optional[str] = None
    google_extension_version: str = "1.0.0"
    google_generative_ai_http_base_url: str = "https://generativelanguage.googleapis.com"
    google_generative_ai_http_alt_base_url: str = "https://generativelanguage.google.com"
    google_generative_ai_http_request_timeout: int = 60000
    google_vertex_ai_http_base_url: str = "https://googleapis.com"
    google_vertex_ai_http_service_name: str = "aiplatform"
    google_vertex_ai_http_service_version: str = "v1beta1"
    google_vertex_ai_location: str = "us-central1"
    google_vertex_ai_project_override: Optional[str] = None
    google_model_id_override: Optional[str] = None
    google_requests_log_enabled: bool = False
    google_log_dir: Optional[str] = None
    google_oauth_client_id: Optional[str] = None
    google_oauth_client_secret: Optional[str] = None
    google_oauth_redirect_port: int = 3456
    google_oauth_redirect_host: str = "localhost"
    google_allowed_mime_types: list = field(default_factory=lambda: [
        "image/png",
        "image/jpeg",
        "image/webp",
        "audio/wav",
        "audio/mp3",
        "audio/mpeg",
        "video/mp4",
        "video/webm",
        "text/plain",
        "application/pdf",
    ])
    google_max_file_size_bytes: int = 20 * 1024 * 1024
    google_max_file_size_strict_bytes: int = 20 * 1024 * 1024
    google_max_video_file_size_bytes: int = 100 * 1024 * 1024
    google_max_audio_file_size_bytes: int = 20 * 1024 * 1024
    google_max_image_file_size_bytes: int = 20 * 1024 * 1024
    google_max_document_file_size_bytes: int = 20 * 1024 * 1024
    google_max_text_file_size_bytes: int = 20 * 1024 * 1024
    google_max_mime_type_bytes: int = 20 * 1024 * 1024
    google_max_media_items_per_request: int = 10
    google_max_generation_files_per_request: int = 10
    google_max_images_per_prompt: int = 10
    google_max_videos_per_prompt: int = 5
    google_max_music_per_prompt: int = 5
    google_max_images_per_batch_request: int = 10
    google_max_generations_per_request: int = 5
    google_max_tokens_text_requests: int = 32000
    google_max_tokens_image_requests: int = 5000
    google_max_tokens_video_requests: int = 5000
    google_max_tokens_audio_requests: int = 5000
    google_max_tokens_classification_requests: int = 5000
    google_max_transcript_chars_for_transcriptions: int = 100000
    google_max_transcript_chars_for_transcription_requests: int = 100000
    google_max_transcript_chars_for_classifications: int = 20000
    google_max_text_length_text: int = 32000
    google_max_text_length_long: int = 200000
    google_max_text_length_media: int = 5000
    google_max_audio_seconds_long: int = 600
    google_max_video_seconds_long: int = 600
    google_max_audio_seconds_short: int = 60
    google_max_video_seconds_short: int = 60
    google_max_audio_transcript_chars: int = 100000
    google_max_video_transcript_chars: int = 100000
    google_max_image_bytes: int = 20 * 1024 * 1024
    google_max_audio_bytes: int = 20 * 1024 * 1024
    google_max_video_bytes: int = 100 * 1024 * 1024
    google_max_document_bytes: int = 20 * 1024 * 1024
    google_max_text_bytes: int = 20 * 1024 * 1024
    google_max_text_chars: int = 100000
    google_max_characters_per_request: int = 100000
    google_max_tokens_total: int = 1048576
    google_max_reasoning_tokens_total: int = 1048576
    google_max_context_tokens_total: int = 1048576
    google_max_candidates_per_request: int = 1
    google_max_images_per_request: int = 1
    google_max_videos_per_request: int = 1
    google_max_music_per_request: int = 1
    google_max_audio_per_request: int = 1
    google_max_speech_per_request: int = 1
    google_max_realtime_connections: int = 1
    google_max_realtime_turns: int = 1
    google_max_realtime_audio_bytes: int = 10 * 1024 * 1024
    google_max_realtime_audio_seconds: int = 3600
    google_max_realtime_text_chars: int = 100000
    google_max_realtime_audio_chars: int = 100000
    google_max_realtime_video_chars: int = 100000
    google_max_realtime_interrupt_events: int = 10
    google_max_realtime_input_audio_buffer_bytes: int = 10 * 1024 * 1024
    google_max_realtime_output_audio_buffer_bytes: int = 10 * 1024 * 1024
    google_max_realtime_interrupt_audio_buffer_bytes: int = 10 * 1024 * 1024
    google_max_realtime_turn_audio_bytes: int = 10 * 1024 * 1024
    google_max_realtime_turn_audio_seconds: int = 600
    google_max_realtime_turn_text_chars: int = 100000
    google_max_realtime_turn_audio_chars: int = 100000
    google_max_realtime_turn_video_chars: int = 100000
    google_max_realtime_turn_events: int = 100
    google_max_realtime_turn_interrupt_events: int = 10
    google_max_realtime_session_events: int = 1000
    google_max_realtime_session_audio_bytes: int = 100 * 1024 * 1024
    google_max_realtime_session_audio_seconds: int = 36000
    google_max_realtime_session_text_chars: int = 1000000
    google_max_realtime_session_audio_chars: int = 1000000
    google_max_realtime_session_video_chars: int = 1000000
    google_max_realtime_session_events: int = 10000
    google_max_realtime_session_interrupt_events: int = 1000
    google_max_realtime_session_audio_buffer_bytes: int = 100 * 1024 * 1024
    google_max_realtime_session_output_audio_buffer_bytes: int = 100 * 1024 * 1024
    google_max_realtime_session_interrupt_audio_buffer_bytes: int = 100 * 1024 * 1024
    google_max_realtime_session_input_audio_buffer_bytes: int = 100 * 1024 * 1024
    google_max_realtime_session_input_audio_seconds: int = 36000
    google_max_realtime_session_output_audio_seconds: int = 36000
    google_max_realtime_session_interrupt_audio_seconds: int = 36000
    google_max_realtime_session_input_text_chars: int = 1000000
    google_max_realtime_session_output_text_chars: int = 1000000
    google_max_realtime_session_interrupt_text_chars: int = 1000000
    google_max_realtime_session_input_audio_chars: int = 1000000
    google_max_realtime_session_output_audio_chars: int = 1000000
    google_max_realtime_session_interrupt_audio_chars: int = 1000000
    google_max_realtime_session_input_video_chars: int = 1000000
    google_max_realtime_session_output_video_chars: int = 1000000
    google_max_realtime_session_interrupt_video_chars: int = 1000000
    google_max_realtime_session_events_per_turn: int = 100
    google_max_realtime_session_audio_bytes_per_turn: int = 10 * 1024 * 1024
    google_max_realtime_session_audio_seconds_per_turn: int = 600
    google_max_realtime_session_text_chars_per_turn: int = 100000
    google_max_realtime_session_audio_chars_per_turn: int = 100000
    google_max_realtime_session_video_chars_per_turn: int = 100000
    google_max_realtime_session_interrupt_events_per_turn: int = 10
    google_max_realtime_session_input_audio_buffer_bytes_per_turn: int = 10 * 1024 * 1024
    google_max_realtime_session_output_audio_buffer_bytes_per_turn: int = 10 * 1024 * 1024
    google_max_realtime_session_interrupt_audio_buffer_bytes_per_turn: int = 10 * 1024 * 1024
    google_max_realtime_session_input_audio_seconds_per_turn: int = 600
    google_max_realtime_session_output_audio_seconds_per_turn: int = 600
    google_max_realtime_session_interrupt_audio_seconds_per_turn: int = 600
    google_max_realtime_session_input_text_chars_per_turn: int = 100000
    google_max_realtime_session_output_text_chars_per_turn: int = 100000
    google_max_realtime_session_interrupt_text_chars_per_turn: int = 100000
    google_max_realtime_session_input_audio_chars_per_turn: int = 100000
    google_max_realtime_session_output_audio_chars_per_turn: int = 100000
    google_max_realtime_session_interrupt_audio_chars_per_turn: int = 100000
    google_max_realtime_session_input_video_chars_per_turn: int = 100000
    google_max_realtime_session_output_video_chars_per_turn: int = 100000
    google_max_realtime_session_interrupt_video_chars_per_turn: int = 100000
    google_max_realtime_turn_audio_bytes_per_turn: int = 10 * 1024 * 1024
    google_max_realtime_turn_audio_seconds_per_turn: int = 600
    google_max_realtime_turn_text_chars_per_turn: int = 100000
    google_max_realtime_turn_audio_chars_per_turn: int = 100000
    google_max_realtime_turn_video_chars_per_turn: int = 100000
    google_max_realtime_turn_events_per_turn: int = 100
    google_max_realtime_turn_interrupt_events_per_turn: int = 10
    google_max_realtime_turn_input_audio_buffer_bytes_per_turn: int = 10 * 1024 * 1024
    google_max_realtime_turn_output_audio_buffer_bytes_per_turn: int = 10 * 1024 * 1024
    google_max_realtime_turn_interrupt_audio_buffer_bytes_per_turn: int = 10 * 1024 * 1024
    google_max_realtime_turn_input_audio_seconds_per_turn: int = 600
    google_max_realtime_turn_output_audio_seconds_per_turn: int = 600
    google_max_realtime_turn_interrupt_audio_seconds_per_turn: int = 600
    google_max_realtime_turn_input_text_chars_per_turn: int = 100000
    google_max_realtime_turn_output_text_chars_per_turn: int = 100000
    google_max_realtime_turn_interrupt_text_chars_per_turn: int = 100000
    google_max_realtime_turn_input_audio_chars_per_turn: int = 100000
    google_max_realtime_turn_output_audio_chars_per_turn: int = 100000
    google_max_realtime_turn_interrupt_audio_chars_per_turn: int = 100000
    google_max_realtime_turn_input_video_chars_per_turn: int = 100000
    google_max_realtime_turn_output_video_chars_per_turn: int = 100000
    google_max_realtime_turn_interrupt_video_chars_per_turn: int = 100000
    google_max_realtime_turn_events_per_turn_total: int = 100
    google_max_realtime_turn_audio_bytes_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_audio_seconds_total: int = 600
    google_max_realtime_turn_text_chars_total: int = 100000
    google_max_realtime_turn_audio_chars_total: int = 100000
    google_max_realtime_turn_video_chars_total: int = 100000
    google_max_realtime_turn_interrupt_events_total: int = 10
    google_max_realtime_turn_input_audio_buffer_bytes_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_output_audio_buffer_bytes_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_interrupt_audio_buffer_bytes_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_input_audio_seconds_total: int = 600
    google_max_realtime_turn_output_audio_seconds_total: int = 600
    google_max_realtime_turn_interrupt_audio_seconds_total: int = 600
    google_max_realtime_turn_input_text_chars_total: int = 100000
    google_max_realtime_turn_output_text_chars_total: int = 100000
    google_max_realtime_turn_interrupt_text_chars_total: int = 100000
    google_max_realtime_turn_input_audio_chars_total: int = 100000
    google_max_realtime_turn_output_audio_chars_total: int = 100000
    google_max_realtime_turn_interrupt_audio_chars_total: int = 100000
    google_max_realtime_turn_input_video_chars_total: int = 100000
    google_max_realtime_turn_output_video_chars_total: int = 100000
    google_max_realtime_turn_interrupt_video_chars_total: int = 100000
    google_max_realtime_turn_events_total: int = 100
    google_max_realtime_session_audio_bytes_total: int = 100 * 1024 * 1024
    google_max_realtime_session_audio_seconds_total: int = 36000
    google_max_realtime_session_text_chars_total: int = 1000000
    google_max_realtime_session_audio_chars_total: int = 1000000
    google_max_realtime_session_video_chars_total: int = 1000000
    google_max_realtime_session_events_total: int = 10000
    google_max_realtime_session_interrupt_events_total: int = 1000
    google_max_realtime_session_audio_buffer_bytes_total: int = 100 * 1024 * 1024
    google_max_realtime_session_output_audio_buffer_bytes_total: int = 100 * 1024 * 1024
    google_max_realtime_session_interrupt_audio_buffer_bytes_total: int = 100 * 1024 * 1024
    google_max_realtime_session_input_audio_buffer_bytes_total: int = 100 * 1024 * 1024
    google_max_realtime_session_input_audio_seconds_total: int = 36000
    google_max_realtime_session_output_audio_seconds_total: int = 36000
    google_max_realtime_session_interrupt_audio_seconds_total: int = 36000
    google_max_realtime_session_input_text_chars_total: int = 1000000
    google_max_realtime_session_output_text_chars_total: int = 1000000
    google_max_realtime_session_interrupt_text_chars_total: int = 1000000
    google_max_realtime_session_input_audio_chars_total: int = 1000000
    google_max_realtime_session_output_audio_chars_total: int = 1000000
    google_max_realtime_session_interrupt_audio_chars_total: int = 1000000
    google_max_realtime_session_input_video_chars_total: int = 1000000
    google_max_realtime_session_output_video_chars_total: int = 1000000
    google_max_realtime_session_interrupt_video_chars_total: int = 1000000
    google_max_realtime_session_events_per_turn_total: int = 100
    google_max_realtime_session_audio_bytes_per_turn_total: int = 10 * 1024 * 1024
    google_max_realtime_session_audio_seconds_per_turn_total: int = 600
    google_max_realtime_session_text_chars_per_turn_total: int = 100000
    google_max_realtime_session_audio_chars_per_turn_total: int = 100000
    google_max_realtime_session_video_chars_per_turn_total: int = 100000
    google_max_realtime_session_interrupt_events_per_turn_total: int = 10
    google_max_realtime_session_input_audio_buffer_bytes_per_turn_total: int = 10 * 1024 * 1024
    google_max_realtime_session_output_audio_buffer_bytes_per_turn_total: int = 10 * 1024 * 1024
    google_max_realtime_session_interrupt_audio_buffer_bytes_per_turn_total: int = 10 * 1024 * 1024
    google_max_realtime_session_input_audio_seconds_per_turn_total: int = 600
    google_max_realtime_session_output_audio_seconds_per_turn_total: int = 600
    google_max_realtime_session_interrupt_audio_seconds_per_turn_total: int = 600
    google_max_realtime_session_input_text_chars_per_turn_total: int = 100000
    google_max_realtime_session_output_text_chars_per_turn_total: int = 100000
    google_max_realtime_session_interrupt_text_chars_per_turn_total: int = 100000
    google_max_realtime_session_input_audio_chars_per_turn_total: int = 100000
    google_max_realtime_session_output_audio_chars_per_turn_total: int = 100000
    google_max_realtime_session_interrupt_audio_chars_per_turn_total: int = 100000
    google_max_realtime_session_input_video_chars_per_turn_total: int = 100000
    google_max_realtime_session_output_video_chars_per_turn_total: int = 100000
    google_max_realtime_session_interrupt_video_chars_per_turn_total: int = 100000
    google_max_realtime_session_events_per_turn_total_total: int = 100
    google_max_realtime_turn_audio_bytes_per_turn_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_audio_seconds_per_turn_total: int = 600
    google_max_realtime_turn_text_chars_per_turn_total: int = 100000
    google_max_realtime_turn_audio_chars_per_turn_total: int = 100000
    google_max_realtime_turn_video_chars_per_turn_total: int = 100000
    google_max_realtime_turn_interrupt_events_per_turn_total: int = 10
    google_max_realtime_turn_input_audio_buffer_bytes_per_turn_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_output_audio_buffer_bytes_per_turn_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_interrupt_audio_buffer_bytes_per_turn_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_input_audio_seconds_per_turn_total: int = 600
    google_max_realtime_turn_output_audio_seconds_per_turn_total: int = 600
    google_max_realtime_turn_interrupt_audio_seconds_per_turn_total: int = 600
    google_max_realtime_turn_input_text_chars_per_turn_total: int = 100000
    google_max_realtime_turn_output_text_chars_per_turn_total: int = 100000
    google_max_realtime_turn_interrupt_text_chars_per_turn_total: int = 100000
    google_max_realtime_turn_input_audio_chars_per_turn_total: int = 100000
    google_max_realtime_turn_output_audio_chars_per_turn_total: int = 100000
    google_max_realtime_turn_interrupt_audio_chars_per_turn_total: int = 100000
    google_max_realtime_turn_input_video_chars_per_turn_total: int = 100000
    google_max_realtime_turn_output_video_chars_per_turn_total: int = 100000
    google_max_realtime_turn_interrupt_video_chars_per_turn_total: int = 100000
    google_max_realtime_turn_events_per_turn_total_total: int = 100
    google_max_realtime_turn_audio_bytes_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_audio_seconds_total_total: int = 600
    google_max_realtime_turn_text_chars_total_total: int = 100000
    google_max_realtime_turn_audio_chars_total_total: int = 100000
    google_max_realtime_turn_video_chars_total_total: int = 100000
    google_max_realtime_turn_interrupt_events_total_total: int = 10
    google_max_realtime_turn_input_audio_buffer_bytes_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_output_audio_buffer_bytes_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_interrupt_audio_buffer_bytes_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_input_audio_seconds_total_total: int = 600
    google_max_realtime_turn_output_audio_seconds_total_total: int = 600
    google_max_realtime_turn_interrupt_audio_seconds_total_total: int = 600
    google_max_realtime_turn_input_text_chars_total_total: int = 100000
    google_max_realtime_turn_output_text_chars_total_total: int = 100000
    google_max_realtime_turn_interrupt_text_chars_total_total: int = 100000
    google_max_realtime_turn_input_audio_chars_total_total: int = 100000
    google_max_realtime_turn_output_audio_chars_total_total: int = 100000
    google_max_realtime_turn_interrupt_audio_chars_total_total: int = 100000
    google_max_realtime_turn_input_video_chars_total_total: int = 100000
    google_max_realtime_turn_output_video_chars_total_total: int = 100000
    google_max_realtime_turn_interrupt_video_chars_total_total: int = 100000
    google_max_realtime_turn_events_total_total_total: int = 100
    google_max_realtime_session_audio_bytes_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_audio_seconds_total_total: int = 36000
    google_max_realtime_session_text_chars_total_total: int = 1000000
    google_max_realtime_session_audio_chars_total_total: int = 1000000
    google_max_realtime_session_video_chars_total_total: int = 1000000
    google_max_realtime_session_events_total_total: int = 10000
    google_max_realtime_session_interrupt_events_total_total: int = 1000
    google_max_realtime_session_audio_buffer_bytes_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_output_audio_buffer_bytes_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_interrupt_audio_buffer_bytes_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_input_audio_buffer_bytes_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_input_audio_seconds_total_total: int = 36000
    google_max_realtime_session_output_audio_seconds_total_total: int = 36000
    google_max_realtime_session_interrupt_audio_seconds_total_total: int = 36000
    google_max_realtime_session_input_text_chars_total_total: int = 1000000
    google_max_realtime_session_output_text_chars_total_total: int = 1000000
    google_max_realtime_session_interrupt_text_chars_total_total: int = 1000000
    google_max_realtime_session_input_audio_chars_total_total: int = 1000000
    google_max_realtime_session_output_audio_chars_total_total: int = 1000000
    google_max_realtime_session_interrupt_audio_chars_total_total: int = 1000000
    google_max_realtime_session_input_video_chars_total_total: int = 1000000
    google_max_realtime_session_output_video_chars_total_total: int = 1000000
    google_max_realtime_session_interrupt_video_chars_total_total: int = 1000000
    google_max_realtime_session_events_per_turn_total_total: int = 100
    google_max_realtime_session_audio_bytes_per_turn_total_total: int = 10 * 1024 * 1024
    google_max_realtime_session_audio_seconds_per_turn_total_total: int = 600
    google_max_realtime_session_text_chars_per_turn_total_total: int = 100000
    google_max_realtime_session_audio_chars_per_turn_total_total: int = 100000
    google_max_realtime_session_video_chars_per_turn_total_total: int = 100000
    google_max_realtime_session_interrupt_events_per_turn_total_total: int = 10
    google_max_realtime_session_input_audio_buffer_bytes_per_turn_total_total: int = 10 * 1024 * 1024
    google_max_realtime_session_output_audio_buffer_bytes_per_turn_total_total: int = 10 * 1024 * 1024
    google_max_realtime_session_interrupt_audio_buffer_bytes_per_turn_total_total: int = 10 * 1024 * 1024
    google_max_realtime_session_input_audio_seconds_per_turn_total_total: int = 600
    google_max_realtime_session_output_audio_seconds_per_turn_total_total: int = 600
    google_max_realtime_session_interrupt_audio_seconds_per_turn_total_total: int = 600
    google_max_realtime_session_input_text_chars_per_turn_total_total: int = 100000
    google_max_realtime_session_output_text_chars_per_turn_total_total: int = 100000
    google_max_realtime_session_interrupt_text_chars_per_turn_total_total: int = 100000
    google_max_realtime_session_input_audio_chars_per_turn_total_total: int = 100000
    google_max_realtime_session_output_audio_chars_per_turn_total_total: int = 100000
    google_max_realtime_session_interrupt_audio_chars_per_turn_total_total: int = 100000
    google_max_realtime_session_input_video_chars_per_turn_total_total: int = 100000
    google_max_realtime_session_output_video_chars_per_turn_total_total: int = 100000
    google_max_realtime_session_interrupt_video_chars_per_turn_total_total: int = 100000
    google_max_realtime_session_events_per_turn_total_total_total: int = 100
    google_max_realtime_turn_audio_bytes_per_turn_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_audio_seconds_per_turn_total_total: int = 600
    google_max_realtime_turn_text_chars_per_turn_total_total: int = 100000
    google_max_realtime_turn_audio_chars_per_turn_total_total: int = 100000
    google_max_realtime_turn_video_chars_per_turn_total_total: int = 100000
    google_max_realtime_turn_interrupt_events_per_turn_total_total: int = 10
    google_max_realtime_turn_input_audio_buffer_bytes_per_turn_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_output_audio_buffer_bytes_per_turn_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_interrupt_audio_buffer_bytes_per_turn_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_input_audio_seconds_per_turn_total_total: int = 600
    google_max_realtime_turn_output_audio_seconds_per_turn_total_total: int = 600
    google_max_realtime_turn_interrupt_audio_seconds_per_turn_total_total: int = 600
    google_max_realtime_turn_input_text_chars_per_turn_total_total: int = 100000
    google_max_realtime_turn_output_text_chars_per_turn_total_total: int = 100000
    google_max_realtime_turn_interrupt_text_chars_per_turn_total_total: int = 100000
    google_max_realtime_turn_input_audio_chars_per_turn_total_total: int = 100000
    google_max_realtime_turn_output_audio_chars_per_turn_total_total: int = 100000
    google_max_realtime_turn_interrupt_audio_chars_per_turn_total_total: int = 100000
    google_max_realtime_turn_input_video_chars_per_turn_total_total: int = 100000
    google_max_realtime_turn_output_video_chars_per_turn_total_total: int = 100000
    google_max_realtime_turn_interrupt_video_chars_per_turn_total_total: int = 100000
    google_max_realtime_turn_events_per_turn_total_total_total: int = 100
    google_max_realtime_turn_audio_bytes_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_audio_seconds_total_total_total: int = 600
    google_max_realtime_turn_text_chars_total_total_total: int = 100000
    google_max_realtime_turn_audio_chars_total_total_total: int = 100000
    google_max_realtime_turn_video_chars_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_events_total_total_total: int = 10
    google_max_realtime_turn_input_audio_buffer_bytes_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_output_audio_buffer_bytes_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_interrupt_audio_buffer_bytes_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_input_audio_seconds_total_total_total: int = 600
    google_max_realtime_turn_output_audio_seconds_total_total_total: int = 600
    google_max_realtime_turn_interrupt_audio_seconds_total_total_total: int = 600
    google_max_realtime_turn_input_text_chars_total_total_total: int = 100000
    google_max_realtime_turn_output_text_chars_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_text_chars_total_total_total: int = 100000
    google_max_realtime_turn_input_audio_chars_total_total_total: int = 100000
    google_max_realtime_turn_output_audio_chars_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_audio_chars_total_total_total: int = 100000
    google_max_realtime_turn_input_video_chars_total_total_total: int = 100000
    google_max_realtime_turn_output_video_chars_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_video_chars_total_total_total: int = 100000
    google_max_realtime_turn_events_total_total_total_total: int = 100
    google_max_realtime_session_audio_bytes_total_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_audio_seconds_total_total_total: int = 36000
    google_max_realtime_session_text_chars_total_total_total: int = 1000000
    google_max_realtime_session_audio_chars_total_total_total: int = 1000000
    google_max_realtime_session_video_chars_total_total_total: int = 1000000
    google_max_realtime_session_events_total_total_total: int = 10000
    google_max_realtime_session_interrupt_events_total_total_total: int = 1000
    google_max_realtime_session_audio_buffer_bytes_total_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_output_audio_buffer_bytes_total_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_interrupt_audio_buffer_bytes_total_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_input_audio_buffer_bytes_total_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_input_audio_seconds_total_total_total: int = 36000
    google_max_realtime_session_output_audio_seconds_total_total_total: int = 36000
    google_max_realtime_session_interrupt_audio_seconds_total_total_total: int = 36000
    google_max_realtime_session_input_text_chars_total_total_total: int = 1000000
    google_max_realtime_session_output_text_chars_total_total_total: int = 1000000
    google_max_realtime_session_interrupt_text_chars_total_total_total: int = 1000000
    google_max_realtime_session_input_audio_chars_total_total_total: int = 1000000
    google_max_realtime_session_output_audio_chars_total_total_total: int = 1000000
    google_max_realtime_session_interrupt_audio_chars_total_total_total: int = 1000000
    google_max_realtime_session_input_video_chars_total_total_total: int = 1000000
    google_max_realtime_session_output_video_chars_total_total_total: int = 1000000
    google_max_realtime_session_interrupt_video_chars_total_total_total: int = 1000000
    google_max_realtime_session_events_per_turn_total_total_total: int = 100
    google_max_realtime_session_audio_bytes_per_turn_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_session_audio_seconds_per_turn_total_total_total: int = 600
    google_max_realtime_session_text_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_audio_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_video_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_interrupt_events_per_turn_total_total_total: int = 10
    google_max_realtime_session_input_audio_buffer_bytes_per_turn_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_session_output_audio_buffer_bytes_per_turn_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_session_interrupt_audio_buffer_bytes_per_turn_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_session_input_audio_seconds_per_turn_total_total_total: int = 600
    google_max_realtime_session_output_audio_seconds_per_turn_total_total_total: int = 600
    google_max_realtime_session_interrupt_audio_seconds_per_turn_total_total_total: int = 600
    google_max_realtime_session_input_text_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_output_text_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_interrupt_text_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_input_audio_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_output_audio_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_interrupt_audio_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_input_video_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_output_video_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_interrupt_video_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_events_per_turn_total_total_total_total: int = 100
    google_max_realtime_turn_audio_bytes_per_turn_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_audio_seconds_per_turn_total_total_total: int = 600
    google_max_realtime_turn_text_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_audio_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_video_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_events_per_turn_total_total_total: int = 10
    google_max_realtime_turn_input_audio_buffer_bytes_per_turn_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_output_audio_buffer_bytes_per_turn_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_interrupt_audio_buffer_bytes_per_turn_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_input_audio_seconds_per_turn_total_total_total: int = 600
    google_max_realtime_turn_output_audio_seconds_per_turn_total_total_total: int = 600
    google_max_realtime_turn_interrupt_audio_seconds_per_turn_total_total_total: int = 600
    google_max_realtime_turn_input_text_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_output_text_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_text_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_input_audio_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_output_audio_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_audio_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_input_video_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_output_video_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_video_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_events_per_turn_total_total_total_total: int = 100
    google_max_realtime_turn_audio_bytes_total_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_audio_seconds_total_total_total_total: int = 600
    google_max_realtime_turn_text_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_audio_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_video_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_events_total_total_total_total: int = 10
    google_max_realtime_turn_input_audio_buffer_bytes_total_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_output_audio_buffer_bytes_total_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_interrupt_audio_buffer_bytes_total_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_input_audio_seconds_total_total_total_total: int = 600
    google_max_realtime_turn_output_audio_seconds_total_total_total_total: int = 600
    google_max_realtime_turn_interrupt_audio_seconds_total_total_total_total: int = 600
    google_max_realtime_turn_input_text_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_output_text_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_text_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_input_audio_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_output_audio_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_audio_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_input_video_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_output_video_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_video_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_events_total_total_total_total_total: int = 100
    google_max_realtime_session_audio_bytes_total_total_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_audio_seconds_total_total_total_total: int = 36000
    google_max_realtime_session_text_chars_total_total_total_total: int = 1000000
    google_max_realtime_session_audio_chars_total_total_total_total: int = 1000000
    google_max_realtime_session_video_chars_total_total_total_total: int = 1000000
    google_max_realtime_session_events_total_total_total_total: int = 10000
    google_max_realtime_session_interrupt_events_total_total_total: int = 1000
    google_max_realtime_session_audio_buffer_bytes_total_total_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_output_audio_buffer_bytes_total_total_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_interrupt_audio_buffer_bytes_total_total_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_input_audio_buffer_bytes_total_total_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_input_audio_seconds_total_total_total_total: int = 36000
    google_max_realtime_session_output_audio_seconds_total_total_total_total: int = 36000
    google_max_realtime_session_interrupt_audio_seconds_total_total_total_total: int = 36000
    google_max_realtime_session_input_text_chars_total_total_total_total: int = 1000000
    google_max_realtime_session_output_text_chars_total_total_total_total: int = 1000000
    google_max_realtime_session_interrupt_text_chars_total_total_total_total: int = 1000000
    google_max_realtime_session_input_audio_chars_total_total_total_total: int = 1000000
    google_max_realtime_session_output_audio_chars_total_total_total_total: int = 1000000
    google_max_realtime_session_interrupt_audio_chars_total_total_total_total: int = 1000000
    google_max_realtime_session_input_video_chars_total_total_total_total: int = 1000000
    google_max_realtime_session_output_video_chars_total_total_total_total: int = 1000000
    google_max_realtime_session_interrupt_video_chars_total_total_total_total: int = 1000000
    google_max_realtime_session_events_per_turn_total_total_total_total: int = 100
    google_max_realtime_session_audio_bytes_per_turn_total_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_session_audio_seconds_per_turn_total_total_total_total: int = 600
    google_max_realtime_session_text_chars_per_turn_total_total_total_total: int = 100000
    google_max_realtime_session_audio_chars_per_turn_total_total_total_total: int = 100000
    google_max_realtime_session_video_chars_per_turn_total_total_total_total: int = 100000
    google_max_realtime_session_interrupt_events_per_turn_total_total_total: int = 10
    google_max_realtime_session_input_audio_buffer_bytes_per_turn_total_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_session_output_audio_buffer_bytes_per_turn_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_session_interrupt_audio_buffer_bytes_per_turn_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_session_input_audio_seconds_per_turn_total_total_total: int = 600
    google_max_realtime_session_output_audio_seconds_per_turn_total_total_total: int = 600
    google_max_realtime_session_interrupt_audio_seconds_per_turn_total_total_total: int = 600
    google_max_realtime_session_input_text_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_output_text_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_interrupt_text_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_input_audio_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_output_audio_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_interrupt_audio_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_input_video_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_output_video_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_interrupt_video_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_session_events_per_turn_total_total_total_total_total: int = 100
    google_max_realtime_turn_audio_bytes_per_turn_total_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_audio_seconds_per_turn_total_total_total_total: int = 600
    google_max_realtime_turn_text_chars_per_turn_total_total_total_total: int = 100000
    google_max_realtime_turn_audio_chars_per_turn_total_total_total_total: int = 100000
    google_max_realtime_turn_video_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_events_per_turn_total_total_total_total: int = 10
    google_max_realtime_turn_input_audio_buffer_bytes_per_turn_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_output_audio_buffer_bytes_per_turn_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_interrupt_audio_buffer_bytes_per_turn_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_input_audio_seconds_per_turn_total_total_total: int = 600
    google_max_realtime_turn_output_audio_seconds_per_turn_total_total_total: int = 600
    google_max_realtime_turn_interrupt_audio_seconds_per_turn_total_total_total: int = 600
    google_max_realtime_turn_input_text_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_output_text_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_text_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_input_audio_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_output_audio_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_audio_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_input_video_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_output_video_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_video_chars_per_turn_total_total_total: int = 100000
    google_max_realtime_turn_events_per_turn_total_total_total_total: int = 100
    google_max_realtime_turn_audio_bytes_total_total_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_audio_seconds_total_total_total_total_total: int = 600
    google_max_realtime_turn_text_chars_total_total_total_total_total: int = 100000
    google_max_realtime_turn_audio_chars_total_total_total_total_total: int = 100000
    google_max_realtime_turn_video_chars_total_total_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_events_total_total_total_total: int = 10
    google_max_realtime_turn_input_audio_buffer_bytes_total_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_output_audio_buffer_bytes_total_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_interrupt_audio_buffer_bytes_total_total_total_total: int = 10 * 1024 * 1024
    google_max_realtime_turn_input_audio_seconds_total_total_total_total: int = 600
    google_max_realtime_turn_output_audio_seconds_total_total_total_total: int = 600
    google_max_realtime_turn_interrupt_audio_seconds_total_total_total_total: int = 600
    google_max_realtime_turn_input_text_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_output_text_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_text_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_input_audio_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_output_audio_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_audio_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_input_video_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_output_video_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_interrupt_video_chars_total_total_total_total: int = 100000
    google_max_realtime_turn_events_total_total_total_total_total: int = 100
    google_max_realtime_session_audio_bytes_total_total_total_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_audio_seconds_total_total_total_total: int = 36000
    google_max_realtime_session_text_chars_total_total_total_total: int = 1000000
    google_max_realtime_session_audio_chars_total_total_total_total: int = 1000000
    google_max_realtime_session_video_chars_total_total_total_total: int = 1000000
    google_max_realtime_session_events_total_total_total_total: int = 10000
    google_max_realtime_session_interrupt_events_total_total_total: int = 1000
    google_max_realtime_session_audio_buffer_bytes_total_total_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_output_audio_buffer_bytes_total_total_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_interrupt_audio_buffer_bytes_total_total_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_input_audio_buffer_bytes_total_total_total: int = 100 * 1024 * 1024
    google_max_realtime_session_input_audio_seconds_total_total_total: int = 36000
    google_max_realtime_session_output_audio_seconds_total_total_total: int = 36000
    google_max_realtime_session_interrupt_audio_seconds_total_total_total: int = 36000
    google_max_realtime_session_input_text_chars_total_total_total: int = 1000000
    google_max_realtime_session_output_text_chars_total_total_total: int = 1000000
    google_max_realtime_session_interrupt_text_chars_total_total_total: int = 1000000
    google_max_realtime_session_input_audio_chars_total_total_total: int = 1000000
    google_max_realtime_session_output_audio_chars_total_total_total: int = 1000000
    google_max_realtime_session_interrupt_audio_chars_total_total_total: int = 1000000
    google_max_realtime_session_input_video_chars_total_total_total: int = 1000000
    google_max_realtime_session_output_video_chars_total_total_total: int = 1000000
    google_max_realtime_session_interrupt_video_chars_total_total_total: int = 1000000

    def get(self, key: str, default=None):
        return self.__dict__.get(key, default)

    def to_dict(self) -> dict:
        result = {}
        for k, v in self.__dict__.items():
            if not k.startswith("_") and v is not None:
                result[k] = v
        return result