"""Gateway auth config utilities materialize token/password SecretRefs only for

Mirrors src/gateway/auth-config-utils.ts.
"""

from __future__ import annotations

from typing import Any

def has_configured_gateway_auth_secret_input(*args: Any, **kwargs: Any) -> Any: ...
def can_materialize_gateway_auth_secret_refs_without_exec(*args: Any, **kwargs: Any) -> Any: ...
async def resolve_gateway_token_secret_ref_value(*args: Any, **kwargs: Any) -> Any: ...
async def resolve_gateway_password_secret_ref_value(*args: Any, **kwargs: Any) -> Any: ...
async def materialize_gateway_auth_secret_refs(*args: Any, **kwargs: Any) -> Any: ...
