"""Boot-run echo guard: tracks the active boot prompt per session key so that

Mirrors src/gateway/boot-echo-guard.ts.
"""

from __future__ import annotations

from typing import Any

def set_boot_echo_context_for_session(*args: Any, **kwargs: Any) -> Any: ...
def clear_boot_echo_context_for_session(*args: Any, **kwargs: Any) -> Any: ...
def get_boot_echo_context_for_session(*args: Any, **kwargs: Any) -> Any: ...
def contains_substantial_boot_echo(*args: Any, **kwargs: Any) -> Any: ...
def strip_boot_echo_from_outbound_text(*args: Any, **kwargs: Any) -> Any: ...
def reset_boot_echo_context_for_tests(*args: Any, **kwargs: Any) -> Any: ...
