"""Gateway RPC call helper.

Mirrors src/gateway/call.ts.
"""

from __future__ import annotations

from typing import Any

testing: Any = None

GatewayRequestFunction = Any
CallGatewayCliOptions = Any
CallGatewayOptions = Any
GatewayTransportErrorKind = Any
GatewayTransportErrorJson = Any
GatewayClientRequestErrorJson = Any
GatewayProbeConnectionDetails = Any

class GatewayTransportError: ...
class GatewayCredentialsRequiredError: ...
class GatewayExplicitAuthRequiredError: ...
class GatewayStoredDeviceAuthUnavailableError: ...
class GatewayLocalBackendSharedAuthUnavailableError: ...

def format_gateway_transport_error_json(*args: Any, **kwargs: Any) -> Any: ...
def format_gateway_client_request_error_json(*args: Any, **kwargs: Any) -> Any: ...
def is_gateway_transport_error(*args: Any, **kwargs: Any) -> Any: ...
def is_gateway_credentials_required_error(*args: Any, **kwargs: Any) -> Any: ...
def is_gateway_explicit_auth_required_error(*args: Any, **kwargs: Any) -> Any: ...
def build_gateway_connection_details(*args: Any, **kwargs: Any) -> Any: ...
def resolve_explicit_gateway_auth(*args: Any, **kwargs: Any) -> Any: ...
def ensure_explicit_gateway_auth(*args: Any, **kwargs: Any) -> Any: ...
def random_idempotency_key(*args: Any, **kwargs: Any) -> Any: ...
async def build_gateway_probe_connection_details(*args: Any, **kwargs: Any) -> Any: ...
async def call_gateway_cli(*args: Any, **kwargs: Any) -> Any: ...
async def call_gateway_least_privilege(*args: Any, **kwargs: Any) -> Any: ...
async def call_gateway(*args: Any, **kwargs: Any) -> Any: ...
