"""Gateway chat/agent abort tracking.

Mirrors src/gateway/chat-abort.ts.
"""

from __future__ import annotations

from typing import Any

ChatAbortControllerEntry = Any
RestartRecoveryCandidate = Any
ChatAbortOps = Any

def is_chat_stop_command_text(*args: Any, **kwargs: Any) -> Any: ...
def resolve_chat_run_expires_at_ms(*args: Any, **kwargs: Any) -> Any: ...
def resolve_agent_run_expires_at_ms(*args: Any, **kwargs: Any) -> Any: ...
def register_chat_abort_controller(*args: Any, **kwargs: Any) -> Any: ...
def resolve_in_flight_run_snapshot(*args: Any, **kwargs: Any) -> Any: ...
def bound_in_flight_run_snapshot_for_chat_history(*args: Any, **kwargs: Any) -> Any: ...
def abort_tracked_chat_run_by_id(*args: Any, **kwargs: Any) -> Any: ...
def abort_chat_run_by_id(*args: Any, **kwargs: Any) -> Any: ...
def update_chat_run_provider(*args: Any, **kwargs: Any) -> Any: ...
def abort_chat_runs_for_provider(*args: Any, **kwargs: Any) -> Any: ...
