"""Gateway chat display projection.

Mirrors src/gateway/chat-display-projection.ts.
"""

from __future__ import annotations

from typing import Any

DEFAULT_CHAT_HISTORY_TEXT_MAX_CHARS: Any = None

def resolve_effective_chat_history_max_chars(*args: Any, **kwargs: Any) -> Any: ...
def is_tool_history_block_type(*args: Any, **kwargs: Any) -> Any: ...
def augment_chat_history_with_canvas_blocks(*args: Any, **kwargs: Any) -> Any: ...
def sanitize_chat_history_messages(*args: Any, **kwargs: Any) -> Any: ...
def drop_pre_session_start_announce_pairs(*args: Any, **kwargs: Any) -> Any: ...
def project_chat_display_messages(*args: Any, **kwargs: Any) -> Any: ...
def project_recent_chat_display_messages(*args: Any, **kwargs: Any) -> Any: ...
def project_chat_display_message(*args: Any, **kwargs: Any) -> Any: ...
