"""Gateway webhook helpers for external hook dispatch into agents and wake flows.

Mirrors src/gateway/hooks.ts.
"""

from __future__ import annotations

from typing import Any

get_hook_channel_error: Any = None
get_hook_agent_policy_error: Any = None
get_hook_session_key_prefix_error: Any = None

HooksConfigResolved = Any
HookAgentDispatchPayload = Any

def resolve_hooks_config(*args: Any, **kwargs: Any) -> Any: ...
def is_session_key_allowed_by_prefix(*args: Any, **kwargs: Any) -> Any: ...
def extract_hook_token(*args: Any, **kwargs: Any) -> Any: ...
def normalize_hook_headers(*args: Any, **kwargs: Any) -> Any: ...
def normalize_wake_payload(*args: Any, **kwargs: Any) -> Any: ...
def resolve_hook_channel(*args: Any, **kwargs: Any) -> Any: ...
def resolve_hook_deliver(*args: Any, **kwargs: Any) -> Any: ...
def resolve_hook_idempotency_key(*args: Any, **kwargs: Any) -> Any: ...
def resolve_hook_target_agent_id(*args: Any, **kwargs: Any) -> Any: ...
def resolve_effective_hook_target_agent_id(*args: Any, **kwargs: Any) -> Any: ...
def is_hook_agent_allowed(*args: Any, **kwargs: Any) -> Any: ...
def resolve_hook_session_key(*args: Any, **kwargs: Any) -> Any: ...
def normalize_hook_dispatch_session_key(*args: Any, **kwargs: Any) -> Any: ...
def normalize_agent_payload(*args: Any, **kwargs: Any) -> Any: ...
async def read_json_body(*args: Any, **kwargs: Any) -> Any: ...
