"""Gateway HTTP request helpers.

Mirrors src/gateway/http-utils.ts.
"""

from __future__ import annotations

from typing import Any

OPENCLAW_MODEL_ID: Any = None
OPENCLAW_DEFAULT_MODEL_ID: Any = None

class UnknownGatewayAgentError: ...
class GatewaySessionKeyOverrideError: ...

def is_unknown_gateway_agent_error(*args: Any, **kwargs: Any) -> Any: ...
def is_gateway_session_key_override_error(*args: Any, **kwargs: Any) -> Any: ...
def resolve_agent_id_from_model(*args: Any, **kwargs: Any) -> Any: ...
def resolve_agent_id_for_request(*args: Any, **kwargs: Any) -> Any: ...
def resolve_gateway_request_context(*args: Any, **kwargs: Any) -> Any: ...
async def resolve_open_ai_compat_model_override(*args: Any, **kwargs: Any) -> Any: ...
