"""Gateway HTTP auth helpers.

Mirrors src/gateway/http-auth-utils.ts.
"""

from __future__ import annotations

from typing import Any

AuthorizedGatewayHttpRequest = Any
GatewayHttpRequestAuthCheckResult = Any

def get_header(*args: Any, **kwargs: Any) -> Any: ...
def get_bearer_token(*args: Any, **kwargs: Any) -> Any: ...
def resolve_http_browser_origin_policy(*args: Any, **kwargs: Any) -> Any: ...
def is_gateway_bearer_http_request(*args: Any, **kwargs: Any) -> Any: ...
def resolve_trusted_http_operator_scopes(*args: Any, **kwargs: Any) -> Any: ...
def resolve_open_ai_compatible_http_operator_scopes(*args: Any, **kwargs: Any) -> Any: ...
def resolve_shared_secret_http_operator_scopes(*args: Any, **kwargs: Any) -> Any: ...
def resolve_http_sender_is_owner(*args: Any, **kwargs: Any) -> Any: ...
def resolve_open_ai_compatible_http_sender_is_owner(*args: Any, **kwargs: Any) -> Any: ...
def authorize_open_ai_compatible_http_model_override(*args: Any, **kwargs: Any) -> Any: ...
async def authorize_gateway_http_request_or_reply(*args: Any, **kwargs: Any) -> Any: ...
async def check_gateway_http_request_auth(*args: Any, **kwargs: Any) -> Any: ...
async def authorize_scoped_gateway_http_request_or_reply(*args: Any, **kwargs: Any) -> Any: ...
