"""Shared Gateway HTTP helpers handle small JSON/text responses, SSE headers,

Mirrors src/gateway/http-common.ts.
"""

from __future__ import annotations

from typing import Any

def set_default_security_headers(*args: Any, **kwargs: Any) -> Any: ...
def send_json(*args: Any, **kwargs: Any) -> Any: ...
def send_text(*args: Any, **kwargs: Any) -> Any: ...
def send_method_not_allowed(*args: Any, **kwargs: Any) -> Any: ...
def send_unauthorized(*args: Any, **kwargs: Any) -> Any: ...
def send_rate_limited(*args: Any, **kwargs: Any) -> Any: ...
def send_gateway_auth_failure(*args: Any, **kwargs: Any) -> Any: ...
def send_invalid_request(*args: Any, **kwargs: Any) -> Any: ...
def build_missing_scope_forbidden_body(*args: Any, **kwargs: Any) -> Any: ...
def send_missing_scope_forbidden(*args: Any, **kwargs: Any) -> Any: ...
def write_done(*args: Any, **kwargs: Any) -> Any: ...
def set_sse_headers(*args: Any, **kwargs: Any) -> Any: ...
def watch_client_disconnect(*args: Any, **kwargs: Any) -> Any: ...
async def read_json_body_or_error(*args: Any, **kwargs: Any) -> Any: ...
