"""Gateway live agent probe helpers.

Mirrors src/gateway/live-agent-probes.ts.
"""

from __future__ import annotations

from typing import Any

CronListJob = Any

def is_claude_like_live_agent(*args: Any, **kwargs: Any) -> Any: ...
def assert_live_image_probe_reply(*args: Any, **kwargs: Any) -> Any: ...
def should_run_live_image_probe(*args: Any, **kwargs: Any) -> Any: ...
def create_live_cron_probe_spec(*args: Any, **kwargs: Any) -> Any: ...
def build_live_cron_probe_message(*args: Any, **kwargs: Any) -> Any: ...
def assert_cron_job_matches(*args: Any, **kwargs: Any) -> Any: ...
async def run_open_claw_cli_json(*args: Any, **kwargs: Any) -> Any: ...
async def assert_cron_job_visible_via_cli(*args: Any, **kwargs: Any) -> Any: ...
