"""MCP loopback HTTP request helpers.

Mirrors src/gateway/mcp-http.request.ts.
"""

from __future__ import annotations

from typing import Any

def validate_mcp_loopback_request(*args: Any, **kwargs: Any) -> Any: ...
def is_mcp_http_body_too_large_error(*args: Any, **kwargs: Any) -> Any: ...
def is_mcp_http_body_timeout_error(*args: Any, **kwargs: Any) -> Any: ...
def resolve_mcp_http_body_timeout_ms(*args: Any, **kwargs: Any) -> Any: ...
def resolve_mcp_cli_capture_key(*args: Any, **kwargs: Any) -> Any: ...
def resolve_mcp_request_context(*args: Any, **kwargs: Any) -> Any: ...
async def read_mcp_http_body(*args: Any, **kwargs: Any) -> Any: ...
