"""Process-local MCP loopback runtime state for owner/non-owner HTTP access.

Mirrors src/gateway/mcp-http.loopback-runtime.ts.
"""

from __future__ import annotations

from typing import Any

McpLoopbackToolCallResult = Any
McpLoopbackToolCallStart = Any
McpLoopbackRequestCaptureHandle = Any
McpLoopbackToolCallCaptureHandle = Any

def begin_mcp_loopback_tool_call_capture(*args: Any, **kwargs: Any) -> Any: ...
def resolve_mcp_loopback_yield_context(*args: Any, **kwargs: Any) -> Any: ...
def mark_mcp_loopback_request_started(*args: Any, **kwargs: Any) -> Any: ...
def mark_mcp_loopback_request_classified(*args: Any, **kwargs: Any) -> Any: ...
def mark_mcp_loopback_request_finished(*args: Any, **kwargs: Any) -> Any: ...
def mark_mcp_loopback_tool_call_started(*args: Any, **kwargs: Any) -> Any: ...
def update_mcp_loopback_tool_call_capture(*args: Any, **kwargs: Any) -> Any: ...
def record_mcp_loopback_tool_call_result(*args: Any, **kwargs: Any) -> Any: ...
def mark_mcp_loopback_tool_call_finished(*args: Any, **kwargs: Any) -> Any: ...
def clear_mcp_loopback_tool_call_capture(*args: Any, **kwargs: Any) -> Any: ...
def clear_mcp_loopback_tool_call_captures_for_test(*args: Any, **kwargs: Any) -> Any: ...
def get_active_mcp_loopback_runtime(*args: Any, **kwargs: Any) -> Any: ...
def set_active_mcp_loopback_runtime(*args: Any, **kwargs: Any) -> Any: ...
def resolve_mcp_loopback_bearer_token(*args: Any, **kwargs: Any) -> Any: ...
def clear_active_mcp_loopback_runtime_by_owner_token(*args: Any, **kwargs: Any) -> Any: ...
def create_mcp_loopback_server_config(*args: Any, **kwargs: Any) -> Any: ...
async def wait_for_mcp_loopback_tool_call_capture_idle(*args: Any, **kwargs: Any) -> Any: ...
