"""Gateway method authorization scope resolver.

Mirrors src/gateway/method-scopes.ts.
"""

from __future__ import annotations

from typing import Any

CLI_DEFAULT_OPERATOR_SCOPES: Any = None

def is_approval_method(*args: Any, **kwargs: Any) -> Any: ...
def is_node_role_method(*args: Any, **kwargs: Any) -> Any: ...
def is_admin_only_method(*args: Any, **kwargs: Any) -> Any: ...
def resolve_required_operator_scope_for_method(*args: Any, **kwargs: Any) -> Any: ...
def resolve_least_privilege_operator_scopes_for_method(*args: Any, **kwargs: Any) -> Any: ...
def authorize_operator_scopes_for_method(*args: Any, **kwargs: Any) -> Any: ...
def authorize_operator_scopes_for_required_scope(*args: Any, **kwargs: Any) -> Any: ...
def is_gateway_method_classified(*args: Any, **kwargs: Any) -> Any: ...
