"""Gateway model-pricing cache state.

Mirrors src/gateway/model-pricing-cache-state.ts.
"""

from __future__ import annotations

from typing import Any

CachedPricingTier = Any
CachedModelPricing = Any
GatewayModelPricingHealth = Any

def replace_gateway_model_pricing_cache(*args: Any, **kwargs: Any) -> Any: ...
def clear_gateway_model_pricing_cache_state(*args: Any, **kwargs: Any) -> Any: ...
def record_gateway_model_pricing_source_failure(*args: Any, **kwargs: Any) -> Any: ...
def clear_gateway_model_pricing_source_failure(*args: Any, **kwargs: Any) -> Any: ...
def clear_gateway_model_pricing_failures(*args: Any, **kwargs: Any) -> Any: ...
def get_gateway_model_pricing_health(*args: Any, **kwargs: Any) -> Any: ...
def get_cached_gateway_model_pricing(*args: Any, **kwargs: Any) -> Any: ...
def get_gateway_model_pricing_cache_meta(*args: Any, **kwargs: Any) -> Any: ...
def get_gateway_model_pricing_cache_fingerprint(*args: Any, **kwargs: Any) -> Any: ...
def reset_gateway_model_pricing_cache_for_test(*args: Any, **kwargs: Any) -> Any: ...
def set_gateway_model_pricing_for_test(*args: Any, **kwargs: Any) -> Any: ...
