"""Gateway network address helpers.

Mirrors src/gateway/net.ts.
"""

from __future__ import annotations

from typing import Any

def pick_primary_lan_i_pv4(*args: Any, **kwargs: Any) -> Any: ...
def normalize_host_header(*args: Any, **kwargs: Any) -> Any: ...
def resolve_host_name(*args: Any, **kwargs: Any) -> Any: ...
def is_loopback_address(*args: Any, **kwargs: Any) -> Any: ...
def resolve_local_interface_address_match(*args: Any, **kwargs: Any) -> Any: ...
def is_private_or_loopback_address(*args: Any, **kwargs: Any) -> Any: ...
def is_trusted_proxy_address(*args: Any, **kwargs: Any) -> Any: ...
def resolve_client_ip(*args: Any, **kwargs: Any) -> Any: ...
def resolve_request_client_ip(*args: Any, **kwargs: Any) -> Any: ...
def default_gateway_bind_mode(*args: Any, **kwargs: Any) -> Any: ...
def is_valid_i_pv4(*args: Any, **kwargs: Any) -> Any: ...
def is_loopback_host(*args: Any, **kwargs: Any) -> Any: ...
def is_localish_host(*args: Any, **kwargs: Any) -> Any: ...
def is_private_or_loopback_host(*args: Any, **kwargs: Any) -> Any: ...
def is_secure_web_socket_url(*args: Any, **kwargs: Any) -> Any: ...
async def resolve_gateway_bind_host(*args: Any, **kwargs: Any) -> Any: ...
async def resolve_gateway_listen_hosts(*args: Any, **kwargs: Any) -> Any: ...
