"""Gateway node command policy.

Mirrors src/gateway/node-command-policy.ts.
"""

from __future__ import annotations

from typing import Any

DEFAULT_DANGEROUS_NODE_COMMANDS: Any = None

def list_dangerous_plugin_node_commands(*args: Any, **kwargs: Any) -> Any: ...
def is_foreground_restricted_plugin_node_command(*args: Any, **kwargs: Any) -> Any: ...
def resolve_node_command_allowlist(*args: Any, **kwargs: Any) -> Any: ...
def resolve_node_pairing_command_allowlist(*args: Any, **kwargs: Any) -> Any: ...
def normalize_declared_node_commands(*args: Any, **kwargs: Any) -> Any: ...
def is_node_command_allowed(*args: Any, **kwargs: Any) -> Any: ...
