"""Capability-token helpers for plugin-hosted node surfaces.

Mirrors src/gateway/plugin-node-capability.ts.
"""

from __future__ import annotations

from typing import Any

PLUGIN_NODE_CAPABILITY_PATH_PREFIX: Any = None
DEFAULT_PLUGIN_NODE_CAPABILITY_TTL_MS: Any = None

PluginNodeCapabilitySurface = Any
PluginNodeCapabilityClient = Any
NormalizedPluginNodeCapabilityUrl = Any

def index_plugin_node_capability_surfaces(*args: Any, **kwargs: Any) -> Any: ...
def resolve_plugin_node_capability_ttl_ms(*args: Any, **kwargs: Any) -> Any: ...
def resolve_plugin_node_capability_expires_at_ms(*args: Any, **kwargs: Any) -> Any: ...
def mint_plugin_node_capability_token(*args: Any, **kwargs: Any) -> Any: ...
def build_plugin_node_capability_scoped_host_url(*args: Any, **kwargs: Any) -> Any: ...
def replace_plugin_node_capability_in_scoped_host_url(*args: Any, **kwargs: Any) -> Any: ...
def normalize_plugin_node_capability_scoped_url(*args: Any, **kwargs: Any) -> Any: ...
def set_client_plugin_node_capability(*args: Any, **kwargs: Any) -> Any: ...
def refresh_client_plugin_node_capability(*args: Any, **kwargs: Any) -> Any: ...
def has_authorized_plugin_node_capability(*args: Any, **kwargs: Any) -> Any: ...
