"""Gateway probe auth resolver.

Mirrors src/gateway/probe-auth.ts.
"""

from __future__ import annotations

from typing import Any

def resolve_gateway_probe_credential_config(*args: Any, **kwargs: Any) -> Any: ...
def resolve_gateway_probe_auth(*args: Any, **kwargs: Any) -> Any: ...
def resolve_gateway_probe_auth_safe(*args: Any, **kwargs: Any) -> Any: ...
async def resolve_gateway_probe_auth_with_secret_inputs(*args: Any, **kwargs: Any) -> Any: ...
async def resolve_gateway_probe_auth_safe_with_secret_inputs(*args: Any, **kwargs: Any) -> Any: ...
