"""Gateway restart timing trace helpers.

Mirrors src/gateway/restart-trace.ts.
"""

from __future__ import annotations

from typing import Any

GatewayRestartTraceHandoff = Any

def start_gateway_restart_trace(*args: Any, **kwargs: Any) -> Any: ...
def mark_gateway_restart_trace(*args: Any, **kwargs: Any) -> Any: ...
def finish_gateway_restart_trace(*args: Any, **kwargs: Any) -> Any: ...
def record_gateway_restart_trace(*args: Any, **kwargs: Any) -> Any: ...
def record_gateway_restart_trace_span(*args: Any, **kwargs: Any) -> Any: ...
def record_gateway_restart_trace_detail(*args: Any, **kwargs: Any) -> Any: ...
def collect_gateway_process_memory_usage_mb(*args: Any, **kwargs: Any) -> Any: ...
def capture_gateway_restart_trace_handoff(*args: Any, **kwargs: Any) -> Any: ...
def create_gateway_restart_trace_handoff_env(*args: Any, **kwargs: Any) -> Any: ...
def resume_gateway_restart_trace_from_handoff(*args: Any, **kwargs: Any) -> Any: ...
def resume_gateway_restart_trace_from_env(*args: Any, **kwargs: Any) -> Any: ...
def reset_gateway_restart_trace_for_test(*args: Any, **kwargs: Any) -> Any: ...
async def measure_gateway_restart_trace(*args: Any, **kwargs: Any) -> Any: ...
