"""Gateway restart sentinel recovery.

Mirrors src/gateway/server-restart-sentinel.ts.
"""

from __future__ import annotations

from typing import Any

def get_latest_update_restart_sentinel(*args: Any, **kwargs: Any) -> Any: ...
def record_latest_update_restart_sentinel(*args: Any, **kwargs: Any) -> Any: ...
async def recover_pending_restart_continuation_deliveries(*args: Any, **kwargs: Any) -> Any: ...
async def schedule_restart_sentinel_wake(*args: Any, **kwargs: Any) -> Any: ...
async def refresh_latest_update_restart_sentinel(*args: Any, **kwargs: Any) -> Any: ...
