"""Gateway plugin runtime adapter.

Mirrors src/gateway/server-plugins.ts.
"""

from __future__ import annotations

from typing import Any

GatewayMethodDispatchResponse = Any

def set_fallback_gateway_context(*args: Any, **kwargs: Any) -> Any: ...
def set_fallback_gateway_context_resolver(*args: Any, **kwargs: Any) -> Any: ...
def clear_fallback_gateway_context(*args: Any, **kwargs: Any) -> Any: ...
def has_in_process_gateway_context(*args: Any, **kwargs: Any) -> Any: ...
def set_plugin_subagent_override_policies(*args: Any, **kwargs: Any) -> Any: ...
def create_gateway_subagent_runtime(*args: Any, **kwargs: Any) -> Any: ...
def create_gateway_nodes_runtime(*args: Any, **kwargs: Any) -> Any: ...
def load_gateway_plugins(*args: Any, **kwargs: Any) -> Any: ...
async def dispatch_gateway_method_in_process_raw(*args: Any, **kwargs: Any) -> Any: ...
async def dispatch_gateway_method_in_process(*args: Any, **kwargs: Any) -> Any: ...
