"""Session-store key canonicalization across default agents, main aliases, and legacy keys.

Mirrors src/gateway/session-store-key.ts.
"""

from __future__ import annotations

from typing import Any

def canonicalize_session_key_for_agent(*args: Any, **kwargs: Any) -> Any: ...
def resolve_session_store_key(*args: Any, **kwargs: Any) -> Any: ...
def resolve_session_store_agent_id(*args: Any, **kwargs: Any) -> Any: ...
def resolve_stored_session_key_for_agent_store(*args: Any, **kwargs: Any) -> Any: ...
def resolve_stored_session_owner_agent_id(*args: Any, **kwargs: Any) -> Any: ...
def canonicalize_spawned_by_for_agent(*args: Any, **kwargs: Any) -> Any: ...
