"""Gateway session reset/delete service.

Mirrors src/gateway/session-reset-service.ts.
"""

from __future__ import annotations

from typing import Any

DrainActiveSessionsForShutdownResult = Any

def archive_session_transcripts_for_session_detailed(*args: Any, **kwargs: Any) -> Any: ...
def emit_gateway_session_end_plugin_hook(*args: Any, **kwargs: Any) -> Any: ...
def emit_gateway_session_start_plugin_hook(*args: Any, **kwargs: Any) -> Any: ...
async def drain_active_sessions_for_shutdown(*args: Any, **kwargs: Any) -> Any: ...
async def emit_session_unbound_lifecycle_event(*args: Any, **kwargs: Any) -> Any: ...
async def cleanup_session_before_mutation(*args: Any, **kwargs: Any) -> Any: ...
async def emit_gateway_before_reset_plugin_hook(*args: Any, **kwargs: Any) -> Any: ...
async def perform_gateway_session_reset(*args: Any, **kwargs: Any) -> Any: ...
