"""Filesystem session transcript helpers.

Mirrors src/gateway/session-transcript-files.fs.ts.
"""

from __future__ import annotations

from typing import Any

ArchivedSessionTranscript = Any
SessionArchiveCleanupRule = Any

def resolve_session_transcript_candidates(*args: Any, **kwargs: Any) -> Any: ...
def archive_file_on_disk(*args: Any, **kwargs: Any) -> Any: ...
def archive_session_transcripts(*args: Any, **kwargs: Any) -> Any: ...
def archive_session_transcripts_detailed(*args: Any, **kwargs: Any) -> Any: ...
def resolve_stable_session_end_transcript(*args: Any, **kwargs: Any) -> Any: ...
async def resolve_session_transcript_reset_archive_candidates_async(*args: Any, **kwargs: Any) -> Any: ...
async def cleanup_archived_session_transcripts(*args: Any, **kwargs: Any) -> Any: ...
