"""Gateway session lifecycle state projection.

Mirrors src/gateway/session-lifecycle-state.ts.
"""

from __future__ import annotations

from typing import Any

def derive_gateway_session_lifecycle_snapshot(*args: Any, **kwargs: Any) -> Any: ...
def derive_persisted_session_lifecycle_patch(*args: Any, **kwargs: Any) -> Any: ...
def derive_gateway_session_lifecycle_projection_patch(*args: Any, **kwargs: Any) -> Any: ...
def is_restart_recovery_lifecycle_event(*args: Any, **kwargs: Any) -> Any: ...
def is_stale_lifecycle_event_for_session(*args: Any, **kwargs: Any) -> Any: ...
async def persist_gateway_session_lifecycle_event(*args: Any, **kwargs: Any) -> Any: ...
