"""Mirrors src/gateway/session-transcript-readers.ts."""

from __future__ import annotations

from typing import Any

def read_session_messages(*args: Any, **kwargs: Any) -> Any: ...
def read_recent_session_messages(*args: Any, **kwargs: Any) -> Any: ...
def visit_session_messages(*args: Any, **kwargs: Any) -> Any: ...
def read_session_message_count(*args: Any, **kwargs: Any) -> Any: ...
def read_recent_session_messages_with_stats(*args: Any, **kwargs: Any) -> Any: ...
def read_recent_session_transcript_lines(*args: Any, **kwargs: Any) -> Any: ...
def read_session_title_fields_from_transcript(*args: Any, **kwargs: Any) -> Any: ...
def read_first_user_message_from_transcript(*args: Any, **kwargs: Any) -> Any: ...
def read_latest_session_usage_from_transcript(*args: Any, **kwargs: Any) -> Any: ...
def read_recent_session_usage_from_transcript(*args: Any, **kwargs: Any) -> Any: ...
def read_session_preview_items_from_transcript(*args: Any, **kwargs: Any) -> Any: ...
async def read_session_messages_async(*args: Any, **kwargs: Any) -> Any: ...
async def read_session_messages_with_source_async(*args: Any, **kwargs: Any) -> Any: ...
async def read_recent_session_messages_async(*args: Any, **kwargs: Any) -> Any: ...
async def read_session_message_by_id_async(*args: Any, **kwargs: Any) -> Any: ...
async def visit_session_messages_async(*args: Any, **kwargs: Any) -> Any: ...
async def read_session_message_count_async(*args: Any, **kwargs: Any) -> Any: ...
async def read_recent_session_messages_with_stats_async(*args: Any, **kwargs: Any) -> Any: ...
async def read_session_title_fields_from_transcript_async(*args: Any, **kwargs: Any) -> Any: ...
async def read_latest_session_usage_from_transcript_async(*args: Any, **kwargs: Any) -> Any: ...
async def read_recent_session_usage_from_transcript_async(*args: Any, **kwargs: Any) -> Any: ...
async def read_latest_recent_session_usage_from_transcript_async(*args: Any, **kwargs: Any) -> Any: ...
