"""Gateway session listing and projection helpers.

Mirrors src/gateway/session-utils.ts.
"""

from __future__ import annotations

from typing import Any

GatewaySessionStoreTarget = Any
GatewaySessionStoreTargetWithStore = Any

def derive_session_title(*args: Any, **kwargs: Any) -> Any: ...
def resolve_deleted_agent_id_from_session_key(*args: Any, **kwargs: Any) -> Any: ...
def load_session_entry(*args: Any, **kwargs: Any) -> Any: ...
def resolve_freshest_session_store_match_from_store_keys(*args: Any, **kwargs: Any) -> Any: ...
def resolve_freshest_session_entry_from_store_keys(*args: Any, **kwargs: Any) -> Any: ...
def prune_legacy_store_keys(*args: Any, **kwargs: Any) -> Any: ...
def migrate_and_prune_gateway_session_store_key(*args: Any, **kwargs: Any) -> Any: ...
def classify_session_key(*args: Any, **kwargs: Any) -> Any: ...
def parse_group_key(*args: Any, **kwargs: Any) -> Any: ...
def list_agents_for_gateway(*args: Any, **kwargs: Any) -> Any: ...
def resolve_gateway_session_store_target_with_store(*args: Any, **kwargs: Any) -> Any: ...
def resolve_gateway_session_store_target(*args: Any, **kwargs: Any) -> Any: ...
def resolve_gateway_session_thinking_default(*args: Any, **kwargs: Any) -> Any: ...
def get_session_defaults(*args: Any, **kwargs: Any) -> Any: ...
def resolve_session_model_ref(*args: Any, **kwargs: Any) -> Any: ...
def resolve_session_model_identity_ref(*args: Any, **kwargs: Any) -> Any: ...
def resolve_session_display_model_identity_ref(*args: Any, **kwargs: Any) -> Any: ...
def build_gateway_session_row(*args: Any, **kwargs: Any) -> Any: ...
def load_gateway_session_row(*args: Any, **kwargs: Any) -> Any: ...
def build_gateway_session_info(*args: Any, **kwargs: Any) -> Any: ...
def filter_and_sort_session_entries(*args: Any, **kwargs: Any) -> Any: ...
def list_sessions_from_store(*args: Any, **kwargs: Any) -> Any: ...
async def resolve_gateway_model_supports_images(*args: Any, **kwargs: Any) -> Any: ...
async def list_sessions_from_store_async(*args: Any, **kwargs: Any) -> Any: ...
