"""Gateway session compaction checkpoint manager.

Mirrors src/gateway/session-compaction-checkpoints.ts.
"""

from __future__ import annotations

from typing import Any

MAX_COMPACTION_CHECKPOINT_LEAF_SCAN_BYTES: Any = None
MAX_COMPACTION_CHECKPOINT_RETAINED_BYTES_PER_SESSION: Any = None

CapturedCompactionCheckpointSnapshot = Any
CompactionCheckpointForkedTranscript = Any
CompactionCheckpointTranscriptForkResult = Any
CompactionCheckpointSessionMutationResult = Any
BranchCheckpointSessionParams = Any
RestoreCheckpointSessionParams = Any
PersistSessionCompactionCheckpointParams = Any
CompactionCheckpointStore = Any

def resolve_compaction_checkpoint_transcript_position(*args: Any, **kwargs: Any) -> Any: ...
def resolve_session_compaction_checkpoint_reason(*args: Any, **kwargs: Any) -> Any: ...
def create_file_backed_compaction_checkpoint_store(*args: Any, **kwargs: Any) -> Any: ...
def list_session_compaction_checkpoints(*args: Any, **kwargs: Any) -> Any: ...
def get_session_compaction_checkpoint(*args: Any, **kwargs: Any) -> Any: ...
async def read_session_leaf_state_from_transcript_async(*args: Any, **kwargs: Any) -> Any: ...
async def fork_compaction_checkpoint_transcript_async(*args: Any, **kwargs: Any) -> Any: ...
async def capture_compaction_checkpoint_snapshot_async(*args: Any, **kwargs: Any) -> Any: ...
async def cleanup_compaction_checkpoint_snapshot(*args: Any, **kwargs: Any) -> Any: ...
async def persist_session_compaction_checkpoint(*args: Any, **kwargs: Any) -> Any: ...
