"""Gateway Talk realtime relay.

Mirrors src/gateway/talk-realtime-relay.ts.
"""

from __future__ import annotations

from typing import Any

def create_talk_realtime_relay_session(*args: Any, **kwargs: Any) -> Any: ...
def send_talk_realtime_relay_audio(*args: Any, **kwargs: Any) -> Any: ...
def submit_talk_realtime_relay_tool_result(*args: Any, **kwargs: Any) -> Any: ...
def register_talk_realtime_relay_agent_run(*args: Any, **kwargs: Any) -> Any: ...
def cancel_talk_realtime_relay_turn(*args: Any, **kwargs: Any) -> Any: ...
def stop_talk_realtime_relay_session(*args: Any, **kwargs: Any) -> Any: ...
def clear_talk_realtime_relay_sessions_for_test(*args: Any, **kwargs: Any) -> Any: ...
async def steer_talk_realtime_relay_agent_run(*args: Any, **kwargs: Any) -> Any: ...
