"""Gateway Talk handoff registry.

Mirrors src/gateway/talk-handoff.ts.
"""

from __future__ import annotations

from typing import Any

TalkHandoffCreateParams = Any
TalkHandoffRecord = Any
TalkHandoffPublicRecord = Any
TalkHandoffCreateResult = Any
TalkHandoffJoinResult = Any
TalkHandoffRevokeResult = Any
TalkHandoffTurnResult = Any

def create_talk_handoff(*args: Any, **kwargs: Any) -> Any: ...
def get_talk_handoff(*args: Any, **kwargs: Any) -> Any: ...
def join_talk_handoff(*args: Any, **kwargs: Any) -> Any: ...
def start_talk_handoff_turn(*args: Any, **kwargs: Any) -> Any: ...
def end_talk_handoff_turn(*args: Any, **kwargs: Any) -> Any: ...
def cancel_talk_handoff_turn(*args: Any, **kwargs: Any) -> Any: ...
def revoke_talk_handoff(*args: Any, **kwargs: Any) -> Any: ...
def verify_talk_handoff_token(*args: Any, **kwargs: Any) -> Any: ...
def clear_talk_handoffs_for_test(*args: Any, **kwargs: Any) -> Any: ...
