"""Gateway Talk transcription relay.

Mirrors src/gateway/talk-transcription-relay.ts.
"""

from __future__ import annotations

from typing import Any

def create_talk_transcription_relay_session(*args: Any, **kwargs: Any) -> Any: ...
def send_talk_transcription_relay_audio(*args: Any, **kwargs: Any) -> Any: ...
def stop_talk_transcription_relay_session(*args: Any, **kwargs: Any) -> Any: ...
def cancel_talk_transcription_relay_turn(*args: Any, **kwargs: Any) -> Any: ...
def clear_talk_transcription_relay_sessions_for_test(*args: Any, **kwargs: Any) -> Any: ...
