"""Gateway WebSocket log formatting.

Mirrors src/gateway/ws-log.ts.
"""

from __future__ import annotations

from typing import Any

def should_log_ws(*args: Any, **kwargs: Any) -> Any: ...
def short_id(*args: Any, **kwargs: Any) -> Any: ...
def format_for_log(*args: Any, **kwargs: Any) -> Any: ...
def summarize_agent_event_for_ws_log(*args: Any, **kwargs: Any) -> Any: ...
def log_ws(*args: Any, **kwargs: Any) -> Any: ...
