from openclaw.commands.channels import (
    channels_add_command,
    channels_capabilities_command,
    channels_list_command,
    channels_logs_command,
    channels_remove_command,
    channels_resolve_command,
    channels_status_command,
    format_config_channels_status_lines,
    format_gateway_channels_status_lines,
)
from openclaw.commands.doctor import doctor_command
from openclaw.commands.gateway_status import (
    build_gateway_status_warnings,
    infer_ssh_target_from_remote_url,
    is_probe_reachable,
    pick_auto_ssh_target_from_discovery,
    pick_primary_probed_target,
    render_probe_summary_line,
    summarize_gateway_probe_capability,
    write_gateway_status_text,
)
from openclaw.commands.migrate import (
    MigrateApplyOptions,
    migrate_apply,
)
from openclaw.commands.models import (
    MODEL_AVAILABILITY_UNAVAILABLE_CODE,
    apply_default_model_primary_update,
    format_error_with_stack,
    is_local_base_url,
    models_list_command,
    models_set_command,
    models_set_image_command,
    normalize_alias,
    should_fallback_to_auth_heuristics,
    update_config,
)
from openclaw.commands.onboard_non_interactive import (
    onboard_config_write,
    onboard_non_interactive_command,
    onboard_remote_command,
)

__all__ = [
    "MODEL_AVAILABILITY_UNAVAILABLE_CODE",
    "MigrateApplyOptions",
    "apply_default_model_primary_update",
    "build_gateway_status_warnings",
    "channels_add_command",
    "channels_capabilities_command",
    "channels_list_command",
    "channels_logs_command",
    "channels_remove_command",
    "channels_resolve_command",
    "channels_status_command",
    "doctor_command",
    "format_config_channels_status_lines",
    "format_error_with_stack",
    "format_gateway_channels_status_lines",
    "infer_ssh_target_from_remote_url",
    "is_local_base_url",
    "is_probe_reachable",
    "migrate_apply",
    "models_list_command",
    "models_set_command",
    "models_set_image_command",
    "normalize_alias",
    "onboard_config_write",
    "onboard_non_interactive_command",
    "onboard_remote_command",
    "pick_auto_ssh_target_from_discovery",
    "pick_primary_probed_target",
    "render_probe_summary_line",
    "should_fallback_to_auth_heuristics",
    "summarize_gateway_probe_capability",
    "update_config",
    "write_gateway_status_text",
]
